{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"fLancamentoQuirius\",\"fkms_rpa_otif_kbi\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.142.928.0 (25.04)+de52df9f0bb74ad93a80d89c52d63fe6d07e0e1b"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\",\"DaxQueryView_Desktop\"]"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      }
    ],
    "culture": "pt-BR",
    "cultures": [
      {
        "name": "pt-BR",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "26414c7e-8921-4089-b5c5-853b11d77641",
        "fromColumn": "Lançado Quirius",
        "fromTable": "fLancamentoQuirius",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_2444c19a-b7a0-4d4c-8a2b-eebc82084acc"
      },
      {
        "name": "7bd1ebf8-0b6b-4a28-8b9c-b4748022ecc1",
        "fromColumn": "Date",
        "fromTable": "dCalendario",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_9e933f3c-1719-47c5-a911-7812a625a499"
      },
      {
        "name": "705070dc-0232-5634-103b-ae6f3ec16f1a",
        "fromColumn": "Data",
        "fromTable": "fLancamentoQuirius",
        "toColumn": "Date",
        "toTable": "dCalendario"
      },
      {
        "name": "d2fdf298-a544-ba72-d0a6-8849bc6622b0",
        "fromColumn": "data_processamento",
        "fromTable": "fkms_rpa_otif_kbi",
        "toColumn": "Date",
        "toTable": "dCalendario"
      }
    ],
    "sourceQueryCulture": "pt-BR",
    "tables": [
      {
        "name": "DateTableTemplate_aa80d22a-e63b-46d3-9983-9079862d7056",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "91c7a302-aa7a-4dbe-aa05-7eec9ce01451",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "1cbafbb6-7fe8-42c5-9bcc-d4e276b066e4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "0ee48834-e183-449c-8bb0-e89d4df98448",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "227f0034-685b-4a7a-ac20-c359fe177c46",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "49b86044-39b4-4900-96cb-2491afd33d78",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "6976f4fe-05a3-4cc9-a90d-94e773f653e7",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "8a1343fb-47d9-4010-b467-bcf6f73395f6",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "5f400369-aeb6-4149-979c-65e9b6ecf7de",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "535717f4-00d5-44e0-8440-3185d71a7787",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "c0271973-b63f-4459-9908-a004f17d34a3",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "081d4344-5151-4196-909b-7ab838228b5e",
                "ordinal": 3
              }
            ],
            "lineageTag": "86dd8ce4-5bc6-42d5-8fc6-a95cc32c3ab8"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "7e302f1a-87e1-476a-baee-8908f533fd92",
        "partitions": [
          {
            "name": "DateTableTemplate_aa80d22a-e63b-46d3-9983-9079862d7056",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "_Medidas",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "b082479044cb45ac997df4e08485d02e"
          }
        ],
        "columns": [
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "18c4ffdf-07d4-4510-9c0a-9dd0af716f00",
            "sourceColumn": "[Value]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "2c84c17f-0680-452f-9dc8-9ec63ff9459a",
        "measures": [
          {
            "name": "Qtde Notas",
            "description": "COUNTROWS ( fLancamentoQuirius )",
            "displayFolder": "Robo Fiscal - Lancamento Fretes",
            "expression": "COUNTROWS ( fLancamentoQuirius )",
            "formatString": "#,#0",
            "lineageTag": "ca472473-88c6-46a5-8539-22e4fde82c15"
          },
          {
            "name": "% Crescimento Dia",
            "description": [
              "VAR UltimaData =",
              "    CALCULATE (",
              "        MAX ( dCalendario[Date] ),",
              "        FILTER (",
              "            ALL ( dCalendario ),",
              "            dCalendario[Date] < MAX ( dCalendario[Date] )",
              "                && NOT ( ISBLANK ( [Qtde Notas] ) )",
              "        )",
              "    )",
              "VAR QtdeUltimaData =",
              "    CALCULATE ( [Qtde Notas], dCalendario[Date] = UltimaData )",
              "VAR QtdeAtual = [Qtde Notas]",
              "RETURN",
              "    IF (",
              "        NOT ISBLANK ( QtdeUltimaData ),",
              "        DIVIDE ( QtdeAtual - QtdeUltimaData, QtdeUltimaData, 0 ),",
              "        BLANK ()",
              "    )"
            ],
            "displayFolder": "Robo Fiscal - Lancamento Fretes",
            "expression": [
              "VAR UltimaData =",
              "    CALCULATE (",
              "        MAX ( dCalendario[Date] ),",
              "        FILTER (",
              "            ALL ( dCalendario ),",
              "            dCalendario[Date] < MAX ( dCalendario[Date] )",
              "                && NOT ( ISBLANK ( [Qtde Notas] ) )",
              "        )",
              "    )",
              "VAR QtdeUltimaData =",
              "    CALCULATE ( [Qtde Notas], dCalendario[Date] = UltimaData )",
              "VAR QtdeAtual = [Qtde Notas]",
              "RETURN",
              "    IF (",
              "        NOT ISBLANK ( QtdeUltimaData ),",
              "        DIVIDE ( QtdeAtual - QtdeUltimaData, QtdeUltimaData, 0 ),",
              "        BLANK ()",
              "    )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "d88f893c-4178-4726-85de-a63ed822eeda"
          },
          {
            "name": "_Crescimento (Formatado)",
            "description": [
              "SWITCH (",
              "    TRUE (),",
              "    ISINSCOPE ( fLancamentoQuirius[Hora] ),",
              "        IF (",
              "            [% Crescimento Hora] > 0,",
              "            FORMAT ( [% Crescimento Hora], \"∆ 0%\" ),",
              "            FORMAT ( [% Crescimento Hora], \"∇ 0%\" )",
              "        ),",
              "    ISINSCOPE ( dCalendario[Dia] ),",
              "        IF (",
              "            [% Crescimento Dia] > 0,",
              "            FORMAT ( [% Crescimento Dia], \"∆ 0%\" ),",
              "            FORMAT ( [% Crescimento Dia], \"∇ 0%\" )",
              "        ),",
              "    ISINSCOPE ( dCalendario[Semana] ),",
              "        IF (",
              "            [% Crescimento Semana] > 0,",
              "            FORMAT ( [% Crescimento Semana], \"∆ 0%\" ),",
              "            FORMAT ( [% Crescimento Semana], \"∇ 0%\" )",
              "        ),",
              "    ISINSCOPE ( dCalendario[Mes] ),",
              "        IF (",
              "            [% Crescimento Mes] > 0,",
              "            FORMAT ( [% Crescimento Mes], \"∆ 0%\" ),",
              "            FORMAT ( [% Crescimento Mes], \"∇ 0%\" )",
              "        ),",
              "    BLANK ()",
              ")"
            ],
            "displayFolder": "Robo Fiscal - Lancamento Fretes",
            "expression": [
              "SWITCH (",
              "    TRUE (),",
              "    ISINSCOPE ( fLancamentoQuirius[Hora] ),",
              "        IF (",
              "            [% Crescimento Hora] > 0,",
              "            FORMAT ( [% Crescimento Hora], \"∆ 0%\" ),",
              "            FORMAT ( [% Crescimento Hora], \"∇ 0%\" )",
              "        ),",
              "    ISINSCOPE ( dCalendario[Dia] ),",
              "        IF (",
              "            [% Crescimento Dia] > 0,",
              "            FORMAT ( [% Crescimento Dia], \"∆ 0%\" ),",
              "            FORMAT ( [% Crescimento Dia], \"∇ 0%\" )",
              "        ),",
              "    ISINSCOPE ( dCalendario[Semana] ),",
              "        IF (",
              "            [% Crescimento Semana] > 0,",
              "            FORMAT ( [% Crescimento Semana], \"∆ 0%\" ),",
              "            FORMAT ( [% Crescimento Semana], \"∇ 0%\" )",
              "        ),",
              "    ISINSCOPE ( dCalendario[Mes] ),",
              "        IF (",
              "            [% Crescimento Mes] > 0,",
              "            FORMAT ( [% Crescimento Mes], \"∆ 0%\" ),",
              "            FORMAT ( [% Crescimento Mes], \"∇ 0%\" )",
              "        ),",
              "    BLANK ()",
              ")"
            ],
            "lineageTag": "dc854c0d-34f1-458f-92f2-1e8de3e9b5b6"
          },
          {
            "name": "_Crescimento (Cores)",
            "description": [
              "SWITCH (",
              "    TRUE (),",
              "    ISINSCOPE ( fLancamentoQuirius[Hora] ), IF ( [% Crescimento Hora] < 0.001, \"#FF0000\", \"#008000\" ),",
              "    ISINSCOPE ( dCalendario[Dia] ), IF ( [% Crescimento Dia] < 0.001, \"#FF0000\", \"#008000\" ),",
              "    ISINSCOPE ( dCalendario[Semana] ), IF ( [% Crescimento Semana] < 0.001, \"#FF0000\", \"#008000\" ),",
              "    ISINSCOPE ( dCalendario[Mes] ), IF ( [% Crescimento Mes] < 0.001, \"#FF0000\", \"#008000\" ),",
              "    BLANK ()",
              ")"
            ],
            "detailRowsDefinition": {
              "expression": "x1"
            },
            "displayFolder": "Robo Fiscal - Lancamento Fretes",
            "expression": [
              "SWITCH (",
              "    TRUE (),",
              "    ISINSCOPE ( fLancamentoQuirius[Hora] ), IF ( [% Crescimento Hora] < 0.001, \"#FF0000\", \"#008000\" ),",
              "    ISINSCOPE ( dCalendario[Dia] ), IF ( [% Crescimento Dia] < 0.001, \"#FF0000\", \"#008000\" ),",
              "    ISINSCOPE ( dCalendario[Semana] ), IF ( [% Crescimento Semana] < 0.001, \"#FF0000\", \"#008000\" ),",
              "    ISINSCOPE ( dCalendario[Mes] ), IF ( [% Crescimento Mes] < 0.001, \"#FF0000\", \"#008000\" ),",
              "    BLANK ()",
              ")"
            ],
            "lineageTag": "cfd3bfae-95bf-4db7-a0e3-87ddd4a4cd99"
          },
          {
            "name": "% Crescimento Hora",
            "description": [
              "VAR UltimaDataHora =",
              "    CALCULATE (",
              "        MAX ( fLancamentoQuirius[Hora] ),",
              "        FILTER (",
              "            ALL ( fLancamentoQuirius ),",
              "            fLancamentoQuirius[Hora] < MAX ( fLancamentoQuirius[Hora] )",
              "                && NOT ( ISBLANK ( [Qtde Notas] ) )",
              "        )",
              "    )",
              "VAR QtdeUltimaHora =",
              "    CALCULATE ( [Qtde Notas], fLancamentoQuirius[Hora] = UltimaDataHora )",
              "VAR QtdeAtual = [Qtde Notas]",
              "RETURN",
              "    IF (",
              "        NOT ISBLANK ( QtdeUltimaHora ),",
              "        DIVIDE ( QtdeAtual - QtdeUltimaHora, QtdeUltimaHora, 0 ),",
              "        BLANK ()",
              "    )"
            ],
            "displayFolder": "Robo Fiscal - Lancamento Fretes",
            "expression": [
              "VAR UltimaDataHora =",
              "    CALCULATE (",
              "        MAX ( fLancamentoQuirius[Hora] ),",
              "        FILTER (",
              "            ALL ( fLancamentoQuirius ),",
              "            fLancamentoQuirius[Hora] < MAX ( fLancamentoQuirius[Hora] )",
              "                && NOT ( ISBLANK ( [Qtde Notas] ) )",
              "        )",
              "    )",
              "VAR QtdeUltimaHora =",
              "    CALCULATE ( [Qtde Notas], fLancamentoQuirius[Hora] = UltimaDataHora )",
              "VAR QtdeAtual = [Qtde Notas]",
              "RETURN",
              "    IF (",
              "        NOT ISBLANK ( QtdeUltimaHora ),",
              "        DIVIDE ( QtdeAtual - QtdeUltimaHora, QtdeUltimaHora, 0 ),",
              "        BLANK ()",
              "    )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "d048b22b-a359-4764-9a2a-c2c3e612064b"
          },
          {
            "name": "R$ Est. Economia",
            "description": "DIVIDE ( [Qtde Notas], 50, 0 ) * 60",
            "displayFolder": "Robo Fiscal - Lancamento Fretes",
            "expression": "[(HS) Economia] * 20",
            "formatString": "R$ #,#0.00",
            "lineageTag": "d82ea27e-7b1e-4168-9661-83fc9f385a0c"
          },
          {
            "name": "Último Processo",
            "description": "MAX ( fLancamentoQuirius[Lançado Quirius] )",
            "displayFolder": "Robo Fiscal - Lancamento Fretes",
            "expression": "MAX ( fLancamentoQuirius[Lançado Quirius] )",
            "formatString": "Short Date",
            "lineageTag": "0cd7d9d6-eab3-4940-9035-88338b16154b"
          },
          {
            "name": "% Crescimento Semana",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": [
              "VAR UltimaSemana =",
              "    CALCULATE (",
              "        MAX ( dCalendario[Date] ),",
              "        FILTER (",
              "            ALL ( dCalendario ),",
              "            dCalendario[Date] < MAX ( dCalendario[Date] )",
              "                && WEEKNUM ( dCalendario[Date], 2 ) < WEEKNUM ( MAX ( dCalendario[Date] ), 2 )",
              "                && NOT ( ISBLANK ( [Qtde Notas] ) )",
              "        )",
              "    )",
              "VAR QtdeUltimaSemana =",
              "    CALCULATE ( [Qtde Notas], dCalendario[Date] = UltimaSemana )",
              "VAR QtdeAtual = [Qtde Notas]",
              "RETURN",
              "    IF (",
              "        NOT ISBLANK ( QtdeUltimaSemana ),",
              "        DIVIDE ( QtdeAtual - QtdeUltimaSemana, QtdeUltimaSemana, 0 ),",
              "        BLANK ()",
              "    )"
            ],
            "displayFolder": "Robo Fiscal - Lancamento Fretes",
            "expression": [
              "VAR UltimaSemana =",
              "    CALCULATE (",
              "        MAX ( dCalendario[Date] ),",
              "        FILTER (",
              "            ALL ( dCalendario ),",
              "            dCalendario[Date] < MAX ( dCalendario[Date] )",
              "                && WEEKNUM ( dCalendario[Date], 2 ) < WEEKNUM ( MAX ( dCalendario[Date] ), 2 )",
              "                && NOT ( ISBLANK ( [Qtde Notas] ) )",
              "        )",
              "    )",
              "VAR QtdeUltimaSemana =",
              "    CALCULATE ( [Qtde Notas], dCalendario[Date] = UltimaSemana )",
              "VAR QtdeAtual = [Qtde Notas]",
              "RETURN",
              "    IF (",
              "        NOT ISBLANK ( QtdeUltimaSemana ),",
              "        DIVIDE ( QtdeAtual - QtdeUltimaSemana, QtdeUltimaSemana, 0 ),",
              "        BLANK ()",
              "    )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "1ddda994-4961-4d68-a0d9-335117659753"
          },
          {
            "name": "% Crescimento Mes",
            "description": [
              "VAR UltimoMes =",
              "    CALCULATE (",
              "        MAX ( dCalendario[Date] ),",
              "        FILTER (",
              "            ALL ( dCalendario ),",
              "            dCalendario[Date] < MAX ( dCalendario[Date] )",
              "                && MONTH ( dCalendario[Date] ) < MONTH ( MAX ( dCalendario[Date] ) )",
              "                && YEAR ( dCalendario[Date] ) = YEAR ( MAX ( dCalendario[Date] ) )",
              "                && NOT ( ISBLANK ( [Qtde Notas] ) )",
              "        )",
              "    )",
              "VAR QtdeUltimoMes =",
              "    CALCULATE ( [Qtde Notas], dCalendario[Date] = UltimoMes )",
              "VAR QtdeAtual = [Qtde Notas]",
              "RETURN",
              "    IF (",
              "        NOT ISBLANK ( QtdeUltimoMes ),",
              "        DIVIDE ( QtdeAtual - QtdeUltimoMes, QtdeUltimoMes, 0 ),",
              "        BLANK ()",
              "    )"
            ],
            "displayFolder": "Robo Fiscal - Lancamento Fretes",
            "expression": [
              "VAR UltimoMes =",
              "    MONTH(CALCULATE (",
              "        MAX ( dCalendario[Date] ),",
              "        FILTER (",
              "            ALL ( dCalendario ),",
              "            dCalendario[Date] < MAX ( dCalendario[Date] )",
              "                && MONTH ( dCalendario[Date] ) < MONTH ( MAX ( dCalendario[Date] ) )",
              "                && YEAR ( dCalendario[Date] ) = YEAR ( MAX ( dCalendario[Date] ) )",
              "                && NOT ( ISBLANK ( [Qtde Notas] ) )",
              "        )",
              "    ))",
              "    ",
              "VAR QtdeUltimoMes =",
              "    CALCULATE ( [Qtde Notas], MONTH(dCalendario[Date]) = UltimoMes )",
              "VAR QtdeAtual = [Qtde Notas]",
              "",
              "VAR _Resultado =     IF (",
              "        NOT ISBLANK ( QtdeUltimoMes ),",
              "        DIVIDE ( QtdeAtual - QtdeUltimoMes, QtdeUltimoMes, 0 ),",
              "        BLANK ()",
              "    )",
              "RETURN _Resultado",
              ""
            ],
            "formatString": "0",
            "lineageTag": "5f11f2a9-31dc-4c5f-b514-213aef0e09bd"
          },
          {
            "name": "% Qtde Notas",
            "description": [
              "DIVIDE (",
              "    [Qtde Notas],",
              "    CALCULATE ( [Qtde Notas], ALL ( fLancamentoQuirius ) ),",
              "    0",
              ")"
            ],
            "displayFolder": "Robo Fiscal - Lancamento Fretes",
            "expression": [
              "DIVIDE (",
              "    [Qtde Notas],",
              "    CALCULATE ( [Qtde Notas], ALL ( fLancamentoQuirius ) ),",
              "    0",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "3e783bfc-bca4-4f1e-b163-efebbc86940b"
          },
          {
            "name": "(HS) Economia",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Robo Fiscal - Lancamento Fretes",
            "expression": "DIVIDE([Qtde Notas] * 7,60,0)",
            "lineageTag": "b00a907e-7cc1-4e3f-8e1c-eb0d2229f79b"
          },
          {
            "name": "Qtde Dias Do Último",
            "displayFolder": "Robo Fiscal - Lancamento Fretes",
            "expression": "DATEDIFF([Último Processo], NOW(), DAY)",
            "formatString": "0",
            "lineageTag": "ffd587cb-ac13-41a3-bf05-7582bba5dd08"
          },
          {
            "name": "Qtde Linhas",
            "displayFolder": "Robo Compras - OTIF KBI",
            "expression": "countrows(fkms_rpa_otif_kbi)",
            "lineageTag": "ef6851cb-eb02-42b2-b0c8-3d5142848fda"
          },
          {
            "name": "R$ Est. Economia-kbi",
            "displayFolder": "Robo Compras - OTIF KBI",
            "expression": "sum(fkms_rpa_otif_kbi[estimativa_dinheiro_economizado])",
            "lineageTag": "4ea6d631-a864-476e-bf5d-d6a9793dea1e"
          },
          {
            "name": "(HS) Economia-kbi",
            "displayFolder": "Robo Compras - OTIF KBI",
            "expression": "sum(fkms_rpa_otif_kbi[estimativa_horas_economizadas])",
            "lineageTag": "3b6c85ab-fb28-4cf1-88d7-bbfd188da7a5"
          },
          {
            "name": "Último Processo-kbi",
            "displayFolder": "Robo Compras - OTIF KBI",
            "expression": "max(fkms_rpa_otif_kbi[data_processamento])",
            "formatString": "Short Date",
            "lineageTag": "d3782697-0f6e-49f0-a7f5-188f59eb5e10"
          },
          {
            "name": "Qtde Dias Do Último-kbi",
            "displayFolder": "Robo Compras - OTIF KBI",
            "expression": "DATEDIFF([Último Processo-kbi], NOW(), DAY)",
            "lineageTag": "957b2c2e-c246-4a52-a934-e7dad78e908e"
          },
          {
            "name": "% Qtde Linhas",
            "displayFolder": "Robo Compras - OTIF KBI",
            "expression": [
              "DIVIDE (\r",
              "    [Qtde Linhas],\r",
              "    CALCULATE ( [Qtde Linhas], ALL ( fkms_rpa_otif_kbi ) ),\r",
              "    0\r",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "1f9a5775-dee8-4aa3-b05c-aa542f03917f"
          },
          {
            "name": "% Crescimento Hora-kbi",
            "displayFolder": "Robo Compras - OTIF KBI",
            "expression": [
              "VAR UltimaDataHora =",
              "    CALCULATE (",
              "        MAX ( fkms_rpa_otif_kbi[hora_processamento] ),",
              "        FILTER (",
              "            ALL ( fkms_rpa_otif_kbi ),",
              "            fkms_rpa_otif_kbi[hora_processamento] < MAX ( fkms_rpa_otif_kbi[hora_processamento] )",
              "                && NOT ( ISBLANK ( [Qtde Linhas] ) )",
              "        )",
              "    )",
              "VAR QtdeUltimaHora =",
              "    CALCULATE ( [Qtde Linhas], fkms_rpa_otif_kbi[hora_processamento] = UltimaDataHora )",
              "VAR QtdeAtual = [Qtde Linhas]",
              "RETURN",
              "    IF (",
              "        NOT ISBLANK ( QtdeUltimaHora ),",
              "        DIVIDE ( QtdeAtual - QtdeUltimaHora, QtdeUltimaHora, 0 ),",
              "        BLANK ()",
              "    )"
            ],
            "lineageTag": "823a8330-8d69-4eff-9b13-ab364095826b"
          },
          {
            "name": "% Crescimento Dia-kbi",
            "displayFolder": "Robo Compras - OTIF KBI",
            "expression": [
              "VAR UltimaData =",
              "    CALCULATE (",
              "        MAX ( dCalendario[Date] ),",
              "        FILTER (",
              "            ALL ( dCalendario ),",
              "            dCalendario[Date] < MAX ( dCalendario[Date] )",
              "                && NOT ( ISBLANK ( [Qtde Linhas] ) )",
              "        )",
              "    )",
              "VAR QtdeUltimaData =",
              "    CALCULATE ( [Qtde Linhas], dCalendario[Date] = UltimaData )",
              "VAR QtdeAtual = [Qtde Linhas]",
              "RETURN",
              "    IF (",
              "        NOT ISBLANK ( QtdeUltimaData ),",
              "        DIVIDE ( QtdeAtual - QtdeUltimaData, QtdeUltimaData, 0 ),",
              "        BLANK ()",
              "    )"
            ],
            "lineageTag": "c818bc61-e971-4f73-87c4-ece45f87a9f2"
          },
          {
            "name": "% Crescimento Semana-kbi",
            "displayFolder": "Robo Compras - OTIF KBI",
            "expression": [
              "VAR UltimaSemana =",
              "    CALCULATE (",
              "        MAX ( dCalendario[Date] ),",
              "        FILTER (",
              "            ALL ( dCalendario ),",
              "            dCalendario[Date] < MAX ( dCalendario[Date] )",
              "                && WEEKNUM ( dCalendario[Date], 2 ) < WEEKNUM ( MAX ( dCalendario[Date] ), 2 )",
              "                && NOT ( ISBLANK ( [Qtde Linhas] ) )",
              "        )",
              "    )",
              "VAR QtdeUltimaSemana =",
              "    CALCULATE ( [Qtde Linhas], dCalendario[Date] = UltimaSemana )",
              "VAR QtdeAtual = [Qtde Linhas]",
              "RETURN",
              "    IF (",
              "        NOT ISBLANK ( QtdeUltimaSemana ),",
              "        DIVIDE ( QtdeAtual - QtdeUltimaSemana, QtdeUltimaSemana, 0 ),",
              "        BLANK ()",
              "    )"
            ],
            "lineageTag": "fddb5f53-7424-4dab-a3af-ccc2f47f3997"
          },
          {
            "name": "% Crescimento Mes-kbi",
            "displayFolder": "Robo Compras - OTIF KBI",
            "expression": [
              "VAR UltimoMes =",
              "    MONTH(CALCULATE (",
              "        MAX ( dCalendario[Date] ),",
              "        FILTER (",
              "            ALL ( dCalendario ),",
              "            dCalendario[Date] < MAX ( dCalendario[Date] )",
              "                && MONTH ( dCalendario[Date] ) < MONTH ( MAX ( dCalendario[Date] ) )",
              "                && YEAR ( dCalendario[Date] ) = YEAR ( MAX ( dCalendario[Date] ) )",
              "                && NOT ( ISBLANK ( [Qtde Linhas] ) )",
              "        )",
              "    ))",
              "    ",
              "VAR QtdeUltimoMes =",
              "    CALCULATE ( [Qtde Linhas], MONTH(dCalendario[Date]) = UltimoMes )",
              "VAR QtdeAtual = [Qtde Linhas]",
              "",
              "VAR _Resultado =     IF (",
              "        NOT ISBLANK ( QtdeUltimoMes ),",
              "        DIVIDE ( QtdeAtual - QtdeUltimoMes, QtdeUltimoMes, 0 ),",
              "        BLANK ()",
              "    )",
              "RETURN _Resultado",
              ""
            ],
            "lineageTag": "0f46a77c-a662-4978-9100-52e2315bf1b3"
          },
          {
            "name": "_Crescimento (Formatado)-kbi",
            "displayFolder": "Robo Compras - OTIF KBI",
            "expression": [
              "SWITCH (",
              "    TRUE (),",
              "    ISINSCOPE ( fkms_rpa_otif_kbi[hora_processamento] ),",
              "        IF (",
              "            [% Crescimento Hora-kbi] > 0,",
              "            FORMAT ( [% Crescimento Hora-kbi], \"∆ 0%\" ),",
              "            FORMAT ( [% Crescimento Hora-kbi], \"∇ 0%\" )",
              "        ),",
              "    ISINSCOPE ( dCalendario[Dia] ),",
              "        IF (",
              "            [% Crescimento Dia] > 0,",
              "            FORMAT ( [% Crescimento Dia-kbi], \"∆ 0%\" ),",
              "            FORMAT ( [% Crescimento Dia-kbi], \"∇ 0%\" )",
              "        ),",
              "    ISINSCOPE ( dCalendario[Semana] ),",
              "        IF (",
              "            [% Crescimento Semana-kbi] > 0,",
              "            FORMAT ( [% Crescimento Semana-kbi], \"∆ 0%\" ),",
              "            FORMAT ( [% Crescimento Semana-kbi], \"∇ 0%\" )",
              "        ),",
              "    ISINSCOPE ( dCalendario[Mes] ),",
              "        IF (",
              "            [% Crescimento Mes-kbi] > 0,",
              "            FORMAT ( [% Crescimento Mes-kbi], \"∆ 0%\" ),",
              "            FORMAT ( [% Crescimento Mes-kbi], \"∇ 0%\" )",
              "        ),",
              "    BLANK ()",
              ")"
            ],
            "lineageTag": "3904fce5-64ac-42e8-bbca-3b3746886c7d"
          },
          {
            "name": "_Crescimento (Cores)-kbi",
            "displayFolder": "Robo Compras - OTIF KBI",
            "expression": [
              "SWITCH (",
              "    TRUE (),",
              "    ISINSCOPE ( fkms_rpa_otif_kbi[hora_processamento] ), IF ( [% Crescimento Hora-kbi] < 0.001, \"#FF0000\", \"#008000\" ),",
              "    ISINSCOPE ( dCalendario[Dia] ), IF ( [% Crescimento Dia-kbi] < 0.001, \"#FF0000\", \"#008000\" ),",
              "    ISINSCOPE ( dCalendario[Semana] ), IF ( [% Crescimento Semana-kbi] < 0.001, \"#FF0000\", \"#008000\" ),",
              "    ISINSCOPE ( dCalendario[Mes] ), IF ( [% Crescimento Mes-kbi] < 0.001, \"#FF0000\", \"#008000\" ),",
              "    BLANK ()",
              ")"
            ],
            "lineageTag": "7532e8f9-66e5-4daa-bf35-b2ff522e33f8"
          }
        ],
        "partitions": [
          {
            "name": "_Medidas",
            "mode": "import",
            "source": {
              "expression": "{1}",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "dCalendario",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "bbe3b2b1c39b4b3e80be28b82208d4c0"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "0884b860-517a-4922-a41f-f6cd6ba3f774",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_9e933f3c-1719-47c5-a911-7812a625a499"
                },
                "isDefault": true,
                "relationship": "7bd1ebf8-0b6b-4a28-8b9c-b4748022ecc1"
              }
            ]
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "3d5edd69-f89d-4097-9ae1-85679c5587d5",
            "sourceColumn": "[Ano]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Mes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "0fb2020c-75fa-4756-9c4c-386380835dc1",
            "sortByColumn": "IDanoEmes",
            "sourceColumn": "[Mes]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "fce8aab5-f2d1-426a-87fb-325f817f1ffd",
            "sortByColumn": "Date",
            "sourceColumn": "[Dia]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Semana",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "1862008e-43ed-411a-93cd-943548d9787d",
            "sourceColumn": "[Semana]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Dia da Semana",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "3ec2cc61-9271-4f9d-b7d4-56c17b34bcd4",
            "sortByColumn": "Nª Dia da Semana",
            "sourceColumn": "[Dia da Semana]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Nª Dia da Semana",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "4c445a2b-c0a6-42f2-9a82-739475d5972e",
            "sourceColumn": "[Nª Dia da Semana]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "IDanoEmes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "dCalendario[Ano] * 100 +MONTH([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "012f03aa-6259-4d96-9604-27a0f7827555",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "AnoMes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "3439cd9f-4029-42e2-95ba-178eb52c43b7",
            "sourceColumn": "[AnoMes]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Mês e Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "46aa6801-448f-4650-9401-5426210d721c",
            "sourceColumn": "[Mês e Ano]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "SemanaDoMes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "VAR PrimeiraSemanaAno = WEEKNUM(DATE(YEAR([Date]), MONTH([Date]), 1))",
              "VAR SemanaAtualAno = WEEKNUM([Date])",
              "RETURN SemanaAtualAno - PrimeiraSemanaAno"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "d3ffbbaf-6e0c-4adc-811c-7822f56b7197",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "d159c82a-e4b3-4293-aa98-3848f4db8c8c",
        "partitions": [
          {
            "name": "dCalendario",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "VAR _dataMinima = MIN(MIN(fLancamentoQuirius[Lançado Quirius]), MIN(fkms_rpa_otif_kbi[data_processamento]))",
                "VAR _dataMaxima = MAX(MAX(fLancamentoQuirius[Lançado Quirius]), MAX(fkms_rpa_otif_kbi[data_processamento]))",
                "RETURN",
                "ADDCOLUMNS(",
                "    CALENDAR(",
                "        DATE(YEAR(_dataMinima), MONTH(_dataMinima), DAY(_dataMinima)),",
                "        DATE(YEAR(_dataMaxima), MONTH(_dataMaxima), DAY(_dataMaxima))",
                "    ),",
                "    \"Ano\", YEAR([Date]),",
                "    \"Mes\", FORMAT([Date], \"MMM\") & \"/\" & YEAR([Date]),",
                "    \"AnoMes\", YEAR([Date]) * 100 + MONTH([Date]),",
                "    \"Semana\", WEEKNUM([Date]),",
                "    \"Dia\", ",
                "        VAR VdiaMes = DAY([Date])",
                "        VAR VdiaSemana = SWITCH(",
                "            WEEKDAY([Date]),",
                "            1, \"Dom\",",
                "            2, \"Seg\",",
                "            3, \"Ter\",",
                "            4, \"Qua\",",
                "            5, \"Qui\",",
                "            6, \"Sex\",",
                "            7, \"Sáb\"",
                "        )",
                "        RETURN VdiaSemana & \"-\" & VdiaMes,",
                "    \"Dia da Semana\", SWITCH(",
                "            WEEKDAY([Date]),",
                "            1, \"Dom\",",
                "            2, \"Seg\",",
                "            3, \"Ter\",",
                "            4, \"Qua\",",
                "            5, \"Qui\",",
                "            6, \"Sex\",",
                "            7, \"Sáb\"",
                "        ),",
                "    \"Nª Dia da Semana\", WEEKDAY([Date]),",
                "    \"Mês e Ano\", FORMAT([Date], \"DD/YYYY\")",
                ")",
                ""
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "fLancamentoQuirius",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "Lançado Quirius",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "4b4ed59d-1e70-4333-891d-7b420c115c3d",
            "sourceColumn": "Lançado Quirius",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_2444c19a-b7a0-4d4c-8a2b-eebc82084acc"
                },
                "isDefault": true,
                "relationship": "26414c7e-8921-4089-b5c5-853b11d77641"
              }
            ]
          },
          {
            "name": "Ordem",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5190af5b-88cb-4db1-a5c4-02651d7efc94",
            "sourceColumn": "Ordem",
            "summarizeBy": "none"
          },
          {
            "name": "Nº Documento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b23e90da-10be-49cc-b3b8-7e8d9bbbf9f7",
            "sourceColumn": "Nº Documento",
            "summarizeBy": "none"
          },
          {
            "name": "DATA VENCIMENTO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6a984136-31e0-4e2d-87c6-109797f34eb1",
            "sourceColumn": "DATA VENCIMENTO",
            "summarizeBy": "sum"
          },
          {
            "name": "CFOP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b11c33d4-5848-4350-bbfc-33e72bae7e2f",
            "sourceColumn": "CFOP",
            "summarizeBy": "sum"
          },
          {
            "name": "DATA DE EMISSÃO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "53f4247e-d989-484b-b7bd-acda0ff0607a",
            "sourceColumn": "DATA DE EMISSÃO",
            "summarizeBy": "sum"
          },
          {
            "name": "Data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "efe5fe0e-ffad-4384-ae3d-2ab922429333",
            "sourceColumn": "Data",
            "summarizeBy": "none"
          },
          {
            "name": "Hora",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "826e7990-e1ba-4366-ba26-0f1ad377e633",
            "sourceColumn": "Hora",
            "summarizeBy": "sum"
          },
          {
            "name": "Minuto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "439944fd-ff9a-4f82-b446-7e8f5bccd90f",
            "sourceColumn": "Minuto",
            "summarizeBy": "sum"
          },
          {
            "name": "Segundo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "3810f5ae-4996-4d1b-acef-aed5efa93c28",
            "sourceColumn": "Segundo",
            "summarizeBy": "sum"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "947c798a-3550-4430-bf1e-879e386e18d9",
            "sourceColumn": "Mês",
            "summarizeBy": "sum"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "80d194f2-992e-4d3f-b556-02e956acd369",
            "sourceColumn": "Ano",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "c65f66d9-8fb5-4902-b092-0d039fd0f46d",
        "partitions": [
          {
            "name": "fLancamentoQuirius",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Folder.Files(\"\\\\forest.local\\dfs\\Brazil\\Trabalho\\Fin\\Fiscal\\ARQUIVO FRETE RPA\"),",
                "    #\"\\\\forest local\\dfs\\Brazil\\Trabalho\\Fin\\Fiscal\\ARQUIVO FRETE RPA\\Bases\\_database_rpa_fretes xlsx\" = Fonte{[#\"Folder Path\"=\"\\\\forest.local\\dfs\\Brazil\\Trabalho\\Fin\\Fiscal\\ARQUIVO FRETE RPA\\\", Name=\"database_rpa_fretes.xlsx\"]}[Content],",
                "    #\"Pasta de Trabalho Importada do Excel\" = Excel.Workbook(#\"\\\\forest local\\dfs\\Brazil\\Trabalho\\Fin\\Fiscal\\ARQUIVO FRETE RPA\\Bases\\_database_rpa_fretes xlsx\"),",
                "    Sheet1_Sheet = #\"Pasta de Trabalho Importada do Excel\"{[Item=\"Sheet1\", Kind=\"Sheet\"]}[Data],",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(",
                "        #\"Cabeçalhos Promovidos\",",
                "        {",
                "            {\"Lançado Quirius\", type text},",
                "            {\"Lançado Totvs\", type text},",
                "            {\"Ordem\", Int64.Type},",
                "            {\"Nº Documento\", Int64.Type},",
                "            {\"DATA VENCIMENTO\", Int64.Type},",
                "            {\"CFOP\", Int64.Type},",
                "            {\"DATA DE EMISSÃO\", Int64.Type}",
                "        }",
                "    ),",
                "    #\"Valor Substituído\" = Table.ReplaceValue(#\"Tipo Alterado\", \"ok\", \"\", Replacer.ReplaceText, {\"Lançado Quirius\"}),",
                "    #\"Valor Substituído1\" = Table.ReplaceValue(#\"Valor Substituído\", \"Quirius - RPA - \", \"\", Replacer.ReplaceText, {\"Lançado Quirius\"}),",
                "    #\"Linhas Filtradas\" = Table.SelectRows(#\"Valor Substituído1\", each ([Lançado Quirius] <> \"\")),",
                "    #\"Outras Colunas Removidas\" = Table.SelectColumns(",
                "        #\"Linhas Filtradas\",",
                "        {\"Lançado Quirius\", \"Ordem\", \"Nº Documento\", \"DATA VENCIMENTO\", \"CFOP\", \"DATA DE EMISSÃO\"}",
                "    ),",
                "    // Conversão da coluna \"Lançado Quirius\" de texto para datetime",
                "    #\"Lançado Quirius Convertido\" = Table.TransformColumns(",
                "        #\"Outras Colunas Removidas\",",
                "        {",
                "            {\"Lançado Quirius\", each ",
                "                let",
                "                    valorTexto = Text.From(_),              // Garante que o valor seja tratado como texto",
                "                    valorLimpo = Text.Trim(valorTexto),       // Remove espaços em branco",
                "                    // Tenta converter para número (caso o valor seja um serial Excel)",
                "                    valorSerialTry = try Number.FromText(valorLimpo, \"pt-BR\")",
                "                in",
                "                    if valorSerialTry[HasError] then",
                "                        // Se a conversão para número falhar, tenta converter como data/hora já formatada",
                "                        DateTime.FromText(valorLimpo)",
                "                    else",
                "                        let",
                "                            valorSerial = valorSerialTry[Value],",
                "                            diasInteiros = Number.RoundDown(valorSerial),       // Obtém a parte inteira (dias)",
                "                            segundosFracao = (valorSerial - diasInteiros) * 86400 // Converte a fração do dia em segundos",
                "                        in",
                "                            #datetime(1899, 12, 30, 0, 0, 0) + #duration(diasInteiros, 0, 0, segundosFracao)",
                "            , type datetime}",
                "        }",
                "    ),",
                "    #\"Ordem Alterado\" = Table.TransformColumnTypes(#\"Lançado Quirius Convertido\", {",
                "        {\"Ordem\", type text},",
                "        {\"Nº Documento\", type text}",
                "    }),",
                "    #\"Data Inserida\" = Table.AddColumn(#\"Ordem Alterado\", \"Data\", each DateTime.Date([Lançado Quirius]), type date),",
                "    #\"Hora Inserida\" = Table.AddColumn(#\"Data Inserida\", \"Hora\", each Time.Hour([Lançado Quirius]), Int64.Type),",
                "    #\"Minuto Inserido\" = Table.AddColumn(#\"Hora Inserida\", \"Minuto\", each Time.Minute([Lançado Quirius]), Int64.Type),",
                "    #\"Segundo Inserido\" = Table.AddColumn(#\"Minuto Inserido\", \"Segundo\", each Time.Second([Lançado Quirius]), type number),",
                "    #\"Mês Inserido\" = Table.AddColumn(#\"Segundo Inserido\", \"Mês\", each Date.Month([Lançado Quirius]), Int64.Type),",
                "    #\"Ano Inserido\" = Table.AddColumn(#\"Mês Inserido\", \"Ano\", each Date.Year([Lançado Quirius]), Int64.Type),",
                "    #\"Duplicatas Removidas\" = Table.Distinct(#\"Ano Inserido\")",
                "in",
                "    #\"Duplicatas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_2444c19a-b7a0-4d4c-8a2b-eebc82084acc",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "4c0833aa-fe45-4fd2-a3e3-34bf393bfb50",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "f72d7fe0-9bcb-49bd-aa4f-64048de4a0f2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "57573388-79e3-48d4-b319-da95071fde66",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "69ffbdcd-fb49-4489-8b12-40a24be06526",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "d90730d6-0662-4280-bb53-efe2dbdb15c2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "9f3dc66b-d859-4dbe-9772-667789508582",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "651fe6ec-d9ba-49b4-b00b-78c1c59bda10",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "ec77e3bd-4035-406b-a1fa-30ba175bfdda",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "e304f7c4-8d98-4024-8ca8-723d6fe910bc",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "20f25e12-4f09-4a47-850d-c2c07f5498b8",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "8407a262-62cb-495e-aa3a-bfbc0039b944",
                "ordinal": 3
              }
            ],
            "lineageTag": "a6b88e9e-7c85-46e5-9916-c717684ec939"
          }
        ],
        "isHidden": true,
        "lineageTag": "e9c50e0b-1b97-4e8b-9c0f-30e76b6250b5",
        "partitions": [
          {
            "name": "LocalDateTable_2444c19a-b7a0-4d4c-8a2b-eebc82084acc",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('fLancamentoQuirius'[Lançado Quirius])), 1, 1), Date(Year(MAX('fLancamentoQuirius'[Lançado Quirius])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Parâmetro",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "9bbf945d34e84197a83dfb8184c47275"
          }
        ],
        "columns": [
          {
            "name": "Parâmetro",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "4d4711f4-db15-4a27-afa1-eeae47e58d42",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Parâmetro Campos"
                }
              ]
            },
            "sortByColumn": "Parâmetro Pedido",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Parâmetro Campos",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "5cd66cb7-727a-4d7c-a73a-c7129948bb22",
            "sortByColumn": "Parâmetro Pedido",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Parâmetro Pedido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "08dd06ce-e0a1-4f21-a4bb-7b8535dfe32a",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "457bce80-0361-4006-a1c8-c59b1cfa32a0",
        "partitions": [
          {
            "name": "Parâmetro",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Horas Economizadas\", NAMEOF('_Medidas'[(HS) Economia]), 0),",
                "    (\"R$ Est. Economia\", NAMEOF('_Medidas'[R$ Est. Economia]), 1)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "fkms_rpa_otif_kbi",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "qtde_processos_total",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "67efd51a-97b6-4a78-ba59-d0ecae2b3021",
            "sourceColumn": "qtde_processos_total",
            "summarizeBy": "sum"
          },
          {
            "name": "fonte_arquivo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e1010c22-42e9-4511-8ae7-8c057b6ecbf6",
            "sourceColumn": "fonte_arquivo",
            "summarizeBy": "none"
          },
          {
            "name": "qtde_processos_com_variacao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "bded7133-c31e-441e-92b2-d1c01c9ccce8",
            "sourceColumn": "qtde_processos_com_variacao",
            "summarizeBy": "sum"
          },
          {
            "name": "data_processamento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "6a210861-1420-4254-aa77-0cf680c2a8ce",
            "sourceColumn": "data_processamento",
            "summarizeBy": "none"
          },
          {
            "name": "hora_processamento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "4ea4c216-c51b-4a7c-94da-0dafd89f8963",
            "sourceColumn": "hora_processamento",
            "summarizeBy": "none"
          },
          {
            "name": "estimativa_horas_economizadas",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6114f4fa-ba2c-441f-947e-2524a2fed315",
            "sourceColumn": "estimativa_horas_economizadas",
            "summarizeBy": "sum"
          },
          {
            "name": "estimativa_dinheiro_economizado",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "90e1623e-e347-45fb-92b1-027e0808c0f1",
            "sourceColumn": "estimativa_dinheiro_economizado",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "36914237-47b8-4e66-b342-dc674385ce71",
        "partitions": [
          {
            "name": "fkms_rpa_otif_kbi",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Sql.Database(\"10.105.40.196\\powerbi\", \"idba_komatsu\", [Query=\"select * from DIM_RPA_OTIF_KBI\"]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(Fonte,{{\"data_processamento\", type date}})",
                "in",
                "    #\"Tipo Alterado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_9e933f3c-1719-47c5-a911-7812a625a499",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "76341eec-7089-48f6-a89a-55c625bcaac4",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "9cb2df1b-6e9a-4795-bfaf-7cceaae3f79c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "e94ec799-5355-49b4-8074-cf8d26e36d4c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "b8300567-c303-422d-9da6-1ff1af3772c5",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "46ab48a9-1ada-4ea8-8cc9-215e64b96994",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "282df398-89aa-4757-b6b1-17ed8c6b52b8",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "9e108d26-2b5c-46ab-869e-bb0c0806d6d4",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "a6783b17-f18d-4ad8-8fa1-3c6114055efd",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "c7abbb3a-af14-4084-ace9-b64b3c88071c",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "abe8a326-fa8d-4fa0-b3e2-da6d348fde13",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "d368592c-f21a-4d33-bacb-be5909ffa663",
                "ordinal": 3
              }
            ],
            "lineageTag": "8ed97173-4707-4dce-b661-9aba772105a8"
          }
        ],
        "isHidden": true,
        "lineageTag": "4e1bf909-84e1-4a59-ab72-daaabc88da64",
        "partitions": [
          {
            "name": "LocalDateTable_9e933f3c-1719-47c5-a911-7812a625a499",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dCalendario'[Date])), 1, 1), Date(Year(MAX('dCalendario'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Parâmetro 2",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "8cd662cf86f140ffb6c6b4e9b3f4526a"
          }
        ],
        "columns": [
          {
            "name": "Parâmetro",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "8fc82aa0-d13f-4cb7-8f1b-7d784383a3c4",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Parâmetro Campos"
                }
              ]
            },
            "sortByColumn": "Parâmetro Pedido",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Parâmetro Campos",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "20feaf95-dc55-4616-bb7b-0fd2dafee3f2",
            "sortByColumn": "Parâmetro Pedido",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Parâmetro Pedido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "5ade9b46-c6f6-4f81-bf5d-2e01e94f3c72",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "6f8745ed-acf6-479f-b7d5-9b4cd6f22014",
        "partitions": [
          {
            "name": "Parâmetro 2",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"(HS) Economia\", NAMEOF('_Medidas'[(HS) Economia-kbi]), 0),",
                "    (\"R$ Est. Economia\", NAMEOF('_Medidas'[R$ Est. Economia-kbi]), 1)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}