{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"fLancamentoQuirius\",\"kms_rpa_otif_kbi\",\"kms_rpa_lancamento_mla\",\"kms_rpa_axeler\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.143.878.0 (25.05)+b20aa3b866ec1b70879135a4e60e4b1301c75b21"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\",\"DaxQueryView_Desktop\"]"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      }
    ],
    "culture": "pt-BR",
    "cultures": [
      {
        "name": "pt-BR",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "705070dc-0232-5634-103b-ae6f3ec16f1a",
        "fromColumn": "Data",
        "fromTable": "fLancamentoQuirius",
        "toColumn": "Date",
        "toTable": "dCalendario"
      },
      {
        "name": "d2fdf298-a544-ba72-d0a6-8849bc6622b0",
        "fromColumn": "data_processamento",
        "fromTable": "kms_rpa_otif_kbi",
        "toColumn": "Date",
        "toTable": "dCalendario"
      },
      {
        "name": "78ccf1d6-a36e-56df-c34f-6f2a85e4b874",
        "fromColumn": "Data",
        "fromTable": "kms_rpa_lancamento_mla",
        "toColumn": "Date",
        "toTable": "dCalendario"
      },
      {
        "name": "ad16d665-88ee-117b-4cc5-58a08c649c29",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "data_processamento",
        "fromTable": "kms_rpa_axeler",
        "toColumn": "Date",
        "toTable": "dCalendario"
      }
    ],
    "sourceQueryCulture": "pt-BR",
    "tables": [
      {
        "name": "_Medidas",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "b082479044cb45ac997df4e08485d02e"
          }
        ],
        "columns": [
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "18c4ffdf-07d4-4510-9c0a-9dd0af716f00",
            "sourceColumn": "[Value]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "2c84c17f-0680-452f-9dc8-9ec63ff9459a",
        "measures": [
          {
            "name": "Qtde Notas",
            "description": "COUNTROWS ( fLancamentoQuirius )",
            "displayFolder": "Robo Fiscal - Lancamento Fretes",
            "expression": "COUNTROWS ( fLancamentoQuirius )",
            "formatString": "#,#0",
            "lineageTag": "ca472473-88c6-46a5-8539-22e4fde82c15"
          },
          {
            "name": "% Crescimento Dia",
            "description": [
              "VAR UltimaData =",
              "    CALCULATE (",
              "        MAX ( dCalendario[Date] ),",
              "        FILTER (",
              "            ALL ( dCalendario ),",
              "            dCalendario[Date] < MAX ( dCalendario[Date] )",
              "                && NOT ( ISBLANK ( [Qtde Notas] ) )",
              "        )",
              "    )",
              "VAR QtdeUltimaData =",
              "    CALCULATE ( [Qtde Notas], dCalendario[Date] = UltimaData )",
              "VAR QtdeAtual = [Qtde Notas]",
              "RETURN",
              "    IF (",
              "        NOT ISBLANK ( QtdeUltimaData ),",
              "        DIVIDE ( QtdeAtual - QtdeUltimaData, QtdeUltimaData, 0 ),",
              "        BLANK ()",
              "    )"
            ],
            "displayFolder": "Robo Fiscal - Lancamento Fretes",
            "expression": [
              "VAR UltimaData =",
              "    CALCULATE (",
              "        MAX ( dCalendario[Date] ),",
              "        FILTER (",
              "            ALL ( dCalendario ),",
              "            dCalendario[Date] < MAX ( dCalendario[Date] )",
              "                && NOT ( ISBLANK ( [Qtde Notas] ) )",
              "        )",
              "    )",
              "VAR QtdeUltimaData =",
              "    CALCULATE ( [Qtde Notas], dCalendario[Date] = UltimaData )",
              "VAR QtdeAtual = [Qtde Notas]",
              "RETURN",
              "    IF (",
              "        NOT ISBLANK ( QtdeUltimaData ),",
              "        DIVIDE ( QtdeAtual - QtdeUltimaData, QtdeUltimaData, 0 ),",
              "        BLANK ()",
              "    )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "d88f893c-4178-4726-85de-a63ed822eeda"
          },
          {
            "name": "_Crescimento (Formatado)",
            "description": [
              "SWITCH (",
              "    TRUE (),",
              "    ISINSCOPE ( fLancamentoQuirius[Hora] ),",
              "        IF (",
              "            [% Crescimento Hora] > 0,",
              "            FORMAT ( [% Crescimento Hora], \"∆ 0%\" ),",
              "            FORMAT ( [% Crescimento Hora], \"∇ 0%\" )",
              "        ),",
              "    ISINSCOPE ( dCalendario[Dia] ),",
              "        IF (",
              "            [% Crescimento Dia] > 0,",
              "            FORMAT ( [% Crescimento Dia], \"∆ 0%\" ),",
              "            FORMAT ( [% Crescimento Dia], \"∇ 0%\" )",
              "        ),",
              "    ISINSCOPE ( dCalendario[Semana] ),",
              "        IF (",
              "            [% Crescimento Semana] > 0,",
              "            FORMAT ( [% Crescimento Semana], \"∆ 0%\" ),",
              "            FORMAT ( [% Crescimento Semana], \"∇ 0%\" )",
              "        ),",
              "    ISINSCOPE ( dCalendario[Mes] ),",
              "        IF (",
              "            [% Crescimento Mes] > 0,",
              "            FORMAT ( [% Crescimento Mes], \"∆ 0%\" ),",
              "            FORMAT ( [% Crescimento Mes], \"∇ 0%\" )",
              "        ),",
              "    BLANK ()",
              ")"
            ],
            "displayFolder": "Robo Fiscal - Lancamento Fretes",
            "expression": [
              "SWITCH (",
              "    TRUE (),",
              "    ISINSCOPE ( fLancamentoQuirius[Hora] ),",
              "        IF (",
              "            [% Crescimento Hora] > 0,",
              "            FORMAT ( [% Crescimento Hora], \"∆ 0%\" ),",
              "            FORMAT ( [% Crescimento Hora], \"∇ 0%\" )",
              "        ),",
              "    ISINSCOPE ( dCalendario[Dia] ),",
              "        IF (",
              "            [% Crescimento Dia] > 0,",
              "            FORMAT ( [% Crescimento Dia], \"∆ 0%\" ),",
              "            FORMAT ( [% Crescimento Dia], \"∇ 0%\" )",
              "        ),",
              "    ISINSCOPE ( dCalendario[Semana] ),",
              "        IF (",
              "            [% Crescimento Semana] > 0,",
              "            FORMAT ( [% Crescimento Semana], \"∆ 0%\" ),",
              "            FORMAT ( [% Crescimento Semana], \"∇ 0%\" )",
              "        ),",
              "    ISINSCOPE ( dCalendario[Mes] ),",
              "        IF (",
              "            [% Crescimento Mes] > 0,",
              "            FORMAT ( [% Crescimento Mes], \"∆ 0%\" ),",
              "            FORMAT ( [% Crescimento Mes], \"∇ 0%\" )",
              "        ),",
              "    BLANK ()",
              ")"
            ],
            "lineageTag": "dc854c0d-34f1-458f-92f2-1e8de3e9b5b6"
          },
          {
            "name": "_Crescimento (Cores)",
            "description": [
              "SWITCH (",
              "    TRUE (),",
              "    ISINSCOPE ( fLancamentoQuirius[Hora] ), IF ( [% Crescimento Hora] < 0.001, \"#FF0000\", \"#008000\" ),",
              "    ISINSCOPE ( dCalendario[Dia] ), IF ( [% Crescimento Dia] < 0.001, \"#FF0000\", \"#008000\" ),",
              "    ISINSCOPE ( dCalendario[Semana] ), IF ( [% Crescimento Semana] < 0.001, \"#FF0000\", \"#008000\" ),",
              "    ISINSCOPE ( dCalendario[Mes] ), IF ( [% Crescimento Mes] < 0.001, \"#FF0000\", \"#008000\" ),",
              "    BLANK ()",
              ")"
            ],
            "detailRowsDefinition": {
              "expression": "x1"
            },
            "displayFolder": "Robo Fiscal - Lancamento Fretes",
            "expression": [
              "SWITCH (",
              "    TRUE (),",
              "    ISINSCOPE ( fLancamentoQuirius[Hora] ), IF ( [% Crescimento Hora] < 0.001, \"#FF0000\", \"#008000\" ),",
              "    ISINSCOPE ( dCalendario[Dia] ), IF ( [% Crescimento Dia] < 0.001, \"#FF0000\", \"#008000\" ),",
              "    ISINSCOPE ( dCalendario[Semana] ), IF ( [% Crescimento Semana] < 0.001, \"#FF0000\", \"#008000\" ),",
              "    ISINSCOPE ( dCalendario[Mes] ), IF ( [% Crescimento Mes] < 0.001, \"#FF0000\", \"#008000\" ),",
              "    BLANK ()",
              ")"
            ],
            "lineageTag": "cfd3bfae-95bf-4db7-a0e3-87ddd4a4cd99"
          },
          {
            "name": "% Crescimento Hora",
            "description": [
              "VAR UltimaDataHora =",
              "    CALCULATE (",
              "        MAX ( fLancamentoQuirius[Hora] ),",
              "        FILTER (",
              "            ALL ( fLancamentoQuirius ),",
              "            fLancamentoQuirius[Hora] < MAX ( fLancamentoQuirius[Hora] )",
              "                && NOT ( ISBLANK ( [Qtde Notas] ) )",
              "        )",
              "    )",
              "VAR QtdeUltimaHora =",
              "    CALCULATE ( [Qtde Notas], fLancamentoQuirius[Hora] = UltimaDataHora )",
              "VAR QtdeAtual = [Qtde Notas]",
              "RETURN",
              "    IF (",
              "        NOT ISBLANK ( QtdeUltimaHora ),",
              "        DIVIDE ( QtdeAtual - QtdeUltimaHora, QtdeUltimaHora, 0 ),",
              "        BLANK ()",
              "    )"
            ],
            "displayFolder": "Robo Fiscal - Lancamento Fretes",
            "expression": [
              "VAR UltimaDataHora =",
              "    CALCULATE (",
              "        MAX ( fLancamentoQuirius[Hora] ),",
              "        FILTER (",
              "            ALL ( fLancamentoQuirius ),",
              "            fLancamentoQuirius[Hora] < MAX ( fLancamentoQuirius[Hora] )",
              "                && NOT ( ISBLANK ( [Qtde Notas] ) )",
              "        )",
              "    )",
              "VAR QtdeUltimaHora =",
              "    CALCULATE ( [Qtde Notas], fLancamentoQuirius[Hora] = UltimaDataHora )",
              "VAR QtdeAtual = [Qtde Notas]",
              "RETURN",
              "    IF (",
              "        NOT ISBLANK ( QtdeUltimaHora ),",
              "        DIVIDE ( QtdeAtual - QtdeUltimaHora, QtdeUltimaHora, 0 ),",
              "        BLANK ()",
              "    )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "d048b22b-a359-4764-9a2a-c2c3e612064b"
          },
          {
            "name": "R$ Est. Economia",
            "description": "DIVIDE ( [Qtde Notas], 50, 0 ) * 60",
            "displayFolder": "Robo Fiscal - Lancamento Fretes",
            "expression": "[(HS) Economia] * 20",
            "formatString": "R$ #,#0.00",
            "lineageTag": "d82ea27e-7b1e-4168-9661-83fc9f385a0c"
          },
          {
            "name": "Último Processo",
            "description": "MAX ( fLancamentoQuirius[Lançado Quirius] )",
            "displayFolder": "Robo Fiscal - Lancamento Fretes",
            "expression": "MAX ( fLancamentoQuirius[Lançado Quirius] )",
            "formatString": "Short Date",
            "lineageTag": "0cd7d9d6-eab3-4940-9035-88338b16154b"
          },
          {
            "name": "% Crescimento Semana",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": [
              "VAR UltimaSemana =",
              "    CALCULATE (",
              "        MAX ( dCalendario[Date] ),",
              "        FILTER (",
              "            ALL ( dCalendario ),",
              "            dCalendario[Date] < MAX ( dCalendario[Date] )",
              "                && WEEKNUM ( dCalendario[Date], 2 ) < WEEKNUM ( MAX ( dCalendario[Date] ), 2 )",
              "                && NOT ( ISBLANK ( [Qtde Notas] ) )",
              "        )",
              "    )",
              "VAR QtdeUltimaSemana =",
              "    CALCULATE ( [Qtde Notas], dCalendario[Date] = UltimaSemana )",
              "VAR QtdeAtual = [Qtde Notas]",
              "RETURN",
              "    IF (",
              "        NOT ISBLANK ( QtdeUltimaSemana ),",
              "        DIVIDE ( QtdeAtual - QtdeUltimaSemana, QtdeUltimaSemana, 0 ),",
              "        BLANK ()",
              "    )"
            ],
            "displayFolder": "Robo Fiscal - Lancamento Fretes",
            "expression": [
              "VAR UltimaSemana =",
              "    CALCULATE (",
              "        MAX ( dCalendario[Date] ),",
              "        FILTER (",
              "            ALL ( dCalendario ),",
              "            dCalendario[Date] < MAX ( dCalendario[Date] )",
              "                && WEEKNUM ( dCalendario[Date], 2 ) < WEEKNUM ( MAX ( dCalendario[Date] ), 2 )",
              "                && NOT ( ISBLANK ( [Qtde Notas] ) )",
              "        )",
              "    )",
              "VAR QtdeUltimaSemana =",
              "    CALCULATE ( [Qtde Notas], dCalendario[Date] = UltimaSemana )",
              "VAR QtdeAtual = [Qtde Notas]",
              "RETURN",
              "    IF (",
              "        NOT ISBLANK ( QtdeUltimaSemana ),",
              "        DIVIDE ( QtdeAtual - QtdeUltimaSemana, QtdeUltimaSemana, 0 ),",
              "        BLANK ()",
              "    )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "1ddda994-4961-4d68-a0d9-335117659753"
          },
          {
            "name": "% Crescimento Mes",
            "description": [
              "VAR UltimoMes =",
              "    CALCULATE (",
              "        MAX ( dCalendario[Date] ),",
              "        FILTER (",
              "            ALL ( dCalendario ),",
              "            dCalendario[Date] < MAX ( dCalendario[Date] )",
              "                && MONTH ( dCalendario[Date] ) < MONTH ( MAX ( dCalendario[Date] ) )",
              "                && YEAR ( dCalendario[Date] ) = YEAR ( MAX ( dCalendario[Date] ) )",
              "                && NOT ( ISBLANK ( [Qtde Notas] ) )",
              "        )",
              "    )",
              "VAR QtdeUltimoMes =",
              "    CALCULATE ( [Qtde Notas], dCalendario[Date] = UltimoMes )",
              "VAR QtdeAtual = [Qtde Notas]",
              "RETURN",
              "    IF (",
              "        NOT ISBLANK ( QtdeUltimoMes ),",
              "        DIVIDE ( QtdeAtual - QtdeUltimoMes, QtdeUltimoMes, 0 ),",
              "        BLANK ()",
              "    )"
            ],
            "displayFolder": "Robo Fiscal - Lancamento Fretes",
            "expression": [
              "VAR UltimoMes =",
              "    MONTH(CALCULATE (",
              "        MAX ( dCalendario[Date] ),",
              "        FILTER (",
              "            ALL ( dCalendario ),",
              "            dCalendario[Date] < MAX ( dCalendario[Date] )",
              "                && MONTH ( dCalendario[Date] ) < MONTH ( MAX ( dCalendario[Date] ) )",
              "                && YEAR ( dCalendario[Date] ) = YEAR ( MAX ( dCalendario[Date] ) )",
              "                && NOT ( ISBLANK ( [Qtde Notas] ) )",
              "        )",
              "    ))",
              "    ",
              "VAR QtdeUltimoMes =",
              "    CALCULATE ( [Qtde Notas], MONTH(dCalendario[Date]) = UltimoMes )",
              "VAR QtdeAtual = [Qtde Notas]",
              "",
              "VAR _Resultado =     IF (",
              "        NOT ISBLANK ( QtdeUltimoMes ),",
              "        DIVIDE ( QtdeAtual - QtdeUltimoMes, QtdeUltimoMes, 0 ),",
              "        BLANK ()",
              "    )",
              "RETURN _Resultado",
              ""
            ],
            "formatString": "0",
            "lineageTag": "5f11f2a9-31dc-4c5f-b514-213aef0e09bd"
          },
          {
            "name": "% Qtde Notas",
            "description": [
              "DIVIDE (",
              "    [Qtde Notas],",
              "    CALCULATE ( [Qtde Notas], ALL ( fLancamentoQuirius ) ),",
              "    0",
              ")"
            ],
            "displayFolder": "Robo Fiscal - Lancamento Fretes",
            "expression": [
              "DIVIDE (",
              "    [Qtde Notas],",
              "    CALCULATE ( [Qtde Notas], ALL ( fLancamentoQuirius ) ),",
              "    0",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "3e783bfc-bca4-4f1e-b163-efebbc86940b"
          },
          {
            "name": "(HS) Economia",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Robo Fiscal - Lancamento Fretes",
            "expression": "DIVIDE([Qtde Notas] * 7,60,0)",
            "lineageTag": "b00a907e-7cc1-4e3f-8e1c-eb0d2229f79b"
          },
          {
            "name": "Qtde Dias Do Último",
            "displayFolder": "Robo Fiscal - Lancamento Fretes",
            "expression": "DATEDIFF([Último Processo], NOW(), DAY)",
            "formatString": "0",
            "lineageTag": "ffd587cb-ac13-41a3-bf05-7582bba5dd08"
          },
          {
            "name": "Qtde Linhas",
            "displayFolder": "Robo Compras - OTIF KBI",
            "expression": "countrows(kms_rpa_otif_kbi)",
            "lineageTag": "ef6851cb-eb02-42b2-b0c8-3d5142848fda"
          },
          {
            "name": "R$ Est. Economia-kbi",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "displayFolder": "Robo Compras - OTIF KBI",
            "expression": "sum(kms_rpa_otif_kbi[estimativa_dinheiro_economizado])",
            "formatString": "R$ #,#0.00",
            "lineageTag": "4ea6d631-a864-476e-bf5d-d6a9793dea1e"
          },
          {
            "name": "(HS) Economia-kbi",
            "displayFolder": "Robo Compras - OTIF KBI",
            "expression": "sum(kms_rpa_otif_kbi[estimativa_horas_economizadas])",
            "lineageTag": "3b6c85ab-fb28-4cf1-88d7-bbfd188da7a5"
          },
          {
            "name": "Último Processo-kbi",
            "displayFolder": "Robo Compras - OTIF KBI",
            "expression": "max(kms_rpa_otif_kbi[data_processamento])",
            "formatString": "Short Date",
            "lineageTag": "d3782697-0f6e-49f0-a7f5-188f59eb5e10"
          },
          {
            "name": "Qtde Dias Do Último-kbi",
            "displayFolder": "Robo Compras - OTIF KBI",
            "expression": "DATEDIFF([Último Processo-kbi], NOW(), DAY)",
            "lineageTag": "957b2c2e-c246-4a52-a934-e7dad78e908e"
          },
          {
            "name": "% Qtde Linhas",
            "displayFolder": "Robo Compras - OTIF KBI",
            "expression": [
              "DIVIDE (",
              "    [Qtde Linhas],",
              "    CALCULATE ( [Qtde Linhas], ALL ( kms_rpa_otif_kbi ) ),",
              "    0",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "1f9a5775-dee8-4aa3-b05c-aa542f03917f"
          },
          {
            "name": "% Crescimento Hora-kbi",
            "displayFolder": "Robo Compras - OTIF KBI",
            "expression": [
              "VAR UltimaDataHora =",
              "    CALCULATE (",
              "        MAX ( kms_rpa_otif_kbi[hora_processamento] ),",
              "        FILTER (",
              "            ALL ( kms_rpa_otif_kbi ),",
              "            kms_rpa_otif_kbi[hora_processamento] < MAX ( kms_rpa_otif_kbi[hora_processamento] )",
              "                && NOT ( ISBLANK ( [Qtde Linhas] ) )",
              "        )",
              "    )",
              "VAR QtdeUltimaHora =",
              "    CALCULATE ( [Qtde Linhas], kms_rpa_otif_kbi[hora_processamento] = UltimaDataHora )",
              "VAR QtdeAtual = [Qtde Linhas]",
              "RETURN",
              "    IF (",
              "        NOT ISBLANK ( QtdeUltimaHora ),",
              "        DIVIDE ( QtdeAtual - QtdeUltimaHora, QtdeUltimaHora, 0 ),",
              "        BLANK ()",
              "    )"
            ],
            "lineageTag": "823a8330-8d69-4eff-9b13-ab364095826b"
          },
          {
            "name": "% Crescimento Dia-kbi",
            "displayFolder": "Robo Compras - OTIF KBI",
            "expression": [
              "VAR UltimaData =",
              "    CALCULATE (",
              "        MAX ( dCalendario[Date] ),",
              "        FILTER (",
              "            ALL ( dCalendario ),",
              "            dCalendario[Date] < MAX ( dCalendario[Date] )",
              "                && NOT ( ISBLANK ( [Qtde Linhas] ) )",
              "        )",
              "    )",
              "VAR QtdeUltimaData =",
              "    CALCULATE ( [Qtde Linhas], dCalendario[Date] = UltimaData )",
              "VAR QtdeAtual = [Qtde Linhas]",
              "RETURN",
              "    IF (",
              "        NOT ISBLANK ( QtdeUltimaData ),",
              "        DIVIDE ( QtdeAtual - QtdeUltimaData, QtdeUltimaData, 0 ),",
              "        BLANK ()",
              "    )"
            ],
            "lineageTag": "c818bc61-e971-4f73-87c4-ece45f87a9f2"
          },
          {
            "name": "% Crescimento Semana-kbi",
            "displayFolder": "Robo Compras - OTIF KBI",
            "expression": [
              "VAR UltimaSemana =",
              "    CALCULATE (",
              "        MAX ( dCalendario[Date] ),",
              "        FILTER (",
              "            ALL ( dCalendario ),",
              "            dCalendario[Date] < MAX ( dCalendario[Date] )",
              "                && WEEKNUM ( dCalendario[Date], 2 ) < WEEKNUM ( MAX ( dCalendario[Date] ), 2 )",
              "                && NOT ( ISBLANK ( [Qtde Linhas] ) )",
              "        )",
              "    )",
              "VAR QtdeUltimaSemana =",
              "    CALCULATE ( [Qtde Linhas], dCalendario[Date] = UltimaSemana )",
              "VAR QtdeAtual = [Qtde Linhas]",
              "RETURN",
              "    IF (",
              "        NOT ISBLANK ( QtdeUltimaSemana ),",
              "        DIVIDE ( QtdeAtual - QtdeUltimaSemana, QtdeUltimaSemana, 0 ),",
              "        BLANK ()",
              "    )"
            ],
            "lineageTag": "fddb5f53-7424-4dab-a3af-ccc2f47f3997"
          },
          {
            "name": "% Crescimento Mes-kbi",
            "displayFolder": "Robo Compras - OTIF KBI",
            "expression": [
              "VAR UltimoMes =",
              "    MONTH(CALCULATE (",
              "        MAX ( dCalendario[Date] ),",
              "        FILTER (",
              "            ALL ( dCalendario ),",
              "            dCalendario[Date] < MAX ( dCalendario[Date] )",
              "                && MONTH ( dCalendario[Date] ) < MONTH ( MAX ( dCalendario[Date] ) )",
              "                && YEAR ( dCalendario[Date] ) = YEAR ( MAX ( dCalendario[Date] ) )",
              "                && NOT ( ISBLANK ( [Qtde Linhas] ) )",
              "        )",
              "    ))",
              "    ",
              "VAR QtdeUltimoMes =",
              "    CALCULATE ( [Qtde Linhas], MONTH(dCalendario[Date]) = UltimoMes )",
              "VAR QtdeAtual = [Qtde Linhas]",
              "",
              "VAR _Resultado =     IF (",
              "        NOT ISBLANK ( QtdeUltimoMes ),",
              "        DIVIDE ( QtdeAtual - QtdeUltimoMes, QtdeUltimoMes, 0 ),",
              "        BLANK ()",
              "    )",
              "RETURN _Resultado",
              ""
            ],
            "lineageTag": "0f46a77c-a662-4978-9100-52e2315bf1b3"
          },
          {
            "name": "_Crescimento (Formatado)-kbi",
            "displayFolder": "Robo Compras - OTIF KBI",
            "expression": [
              "SWITCH (",
              "    TRUE (),",
              "    ISINSCOPE ( kms_rpa_otif_kbi[hora_processamento] ),",
              "        IF (",
              "            [% Crescimento Hora-kbi] > 0,",
              "            FORMAT ( [% Crescimento Hora-kbi], \"∆ 0%\" ),",
              "            FORMAT ( [% Crescimento Hora-kbi], \"∇ 0%\" )",
              "        ),",
              "    ISINSCOPE ( dCalendario[Dia] ),",
              "        IF (",
              "            [% Crescimento Dia] > 0,",
              "            FORMAT ( [% Crescimento Dia-kbi], \"∆ 0%\" ),",
              "            FORMAT ( [% Crescimento Dia-kbi], \"∇ 0%\" )",
              "        ),",
              "    ISINSCOPE ( dCalendario[Semana] ),",
              "        IF (",
              "            [% Crescimento Semana-kbi] > 0,",
              "            FORMAT ( [% Crescimento Semana-kbi], \"∆ 0%\" ),",
              "            FORMAT ( [% Crescimento Semana-kbi], \"∇ 0%\" )",
              "        ),",
              "    ISINSCOPE ( dCalendario[Mes] ),",
              "        IF (",
              "            [% Crescimento Mes-kbi] > 0,",
              "            FORMAT ( [% Crescimento Mes-kbi], \"∆ 0%\" ),",
              "            FORMAT ( [% Crescimento Mes-kbi], \"∇ 0%\" )",
              "        ),",
              "    BLANK ()",
              ")"
            ],
            "lineageTag": "3904fce5-64ac-42e8-bbca-3b3746886c7d"
          },
          {
            "name": "_Crescimento (Cores)-kbi",
            "displayFolder": "Robo Compras - OTIF KBI",
            "expression": [
              "SWITCH (",
              "    TRUE (),",
              "    ISINSCOPE ( kms_rpa_otif_kbi[hora_processamento] ), IF ( [% Crescimento Hora-kbi] < 0.001, \"#FF0000\", \"#008000\" ),",
              "    ISINSCOPE ( dCalendario[Dia] ), IF ( [% Crescimento Dia-kbi] < 0.001, \"#FF0000\", \"#008000\" ),",
              "    ISINSCOPE ( dCalendario[Semana] ), IF ( [% Crescimento Semana-kbi] < 0.001, \"#FF0000\", \"#008000\" ),",
              "    ISINSCOPE ( dCalendario[Mes] ), IF ( [% Crescimento Mes-kbi] < 0.001, \"#FF0000\", \"#008000\" ),",
              "    BLANK ()",
              ")"
            ],
            "lineageTag": "7532e8f9-66e5-4daa-bf35-b2ff522e33f8"
          },
          {
            "name": "Qtde Linhas-mla",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Robo Compras - MLA",
            "expression": "countrows(kms_rpa_lancamento_mla)",
            "formatString": "#,0",
            "lineageTag": "e01c457d-4940-4c75-a62c-493404265cec"
          },
          {
            "name": "(HS) Economia-mla",
            "displayFolder": "Robo Compras - MLA",
            "expression": "COUNTROWS( DISTINCT(kms_rpa_lancamento_mla[Data]) ) * 2",
            "formatString": "0",
            "lineageTag": "0c05f968-52b9-4fd8-ba88-a3c5045c92b1"
          },
          {
            "name": "R$ Est. Economia-mla",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "displayFolder": "Robo Compras - MLA",
            "expression": "[(HS) Economia-mla] * 20",
            "formatString": "R$ #,#0.00",
            "lineageTag": "5bd979b7-ff6f-48bb-8940-f1f30b00b921"
          },
          {
            "name": "Último Processo-mla",
            "displayFolder": "Robo Compras - MLA",
            "expression": "max(kms_rpa_lancamento_mla[Data])",
            "lineageTag": "abf5182b-2a3d-43d5-8b23-cf70490199b7"
          },
          {
            "name": "Qtde Dias Do Último-mla",
            "displayFolder": "Robo Compras - MLA",
            "expression": "DATEDIFF([Último Processo-mla], NOW(), DAY)",
            "lineageTag": "028b15bd-7684-4090-98a5-ac9ece8de14a"
          },
          {
            "name": "% Qtde Linhas-mla",
            "displayFolder": "Robo Compras - MLA",
            "expression": [
              "DIVIDE (",
              "    [Qtde Linhas-mla],",
              "    CALCULATE ( [Qtde Linhas-mla], REMOVEFILTERS ( 'kms_rpa_lancamento_mla' ) ),",
              "    0",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "bc5a8540-f419-460b-984e-5ce7a488df2d"
          },
          {
            "name": "% Crescimento Hora-mla",
            "displayFolder": "Robo Compras - MLA",
            "expression": [
              "VAR UltimaDataHora =",
              "    CALCULATE (",
              "        MAX ( kms_rpa_lancamento_mla[Hora] ),",
              "        FILTER (",
              "            ALL ( kms_rpa_lancamento_mla ),",
              "            kms_rpa_lancamento_mla[Hora] < MAX ( kms_rpa_lancamento_mla[Hora] )",
              "                && NOT ( ISBLANK ( [Qtde Linhas-mla] ) )",
              "        )",
              "    )",
              "VAR QtdeUltimaHora =",
              "    CALCULATE ( [Qtde Linhas-mla], kms_rpa_lancamento_mla[Hora] = UltimaDataHora )",
              "VAR QtdeAtual = [Qtde Linhas-mla]",
              "RETURN",
              "    IF (",
              "        NOT ISBLANK ( QtdeUltimaHora ),",
              "        DIVIDE ( QtdeAtual - QtdeUltimaHora, QtdeUltimaHora, 0 ),",
              "        BLANK ()",
              "    )"
            ],
            "lineageTag": "7dcfd38e-4220-40ff-9bae-a2af5fc697d1"
          },
          {
            "name": "% Crescimento Dia-mla",
            "displayFolder": "Robo Compras - MLA",
            "expression": [
              "VAR UltimaData =",
              "    CALCULATE (",
              "        MAX ( dCalendario[Date] ),",
              "        FILTER (",
              "            ALL ( dCalendario ),",
              "            dCalendario[Date] < MAX ( dCalendario[Date] )",
              "                && NOT ( ISBLANK ( [Qtde Linhas-mla] ) )",
              "        )",
              "    )",
              "VAR QtdeUltimaData =",
              "    CALCULATE ( [Qtde Linhas-mla], dCalendario[Date] = UltimaData )",
              "VAR QtdeAtual = [Qtde Linhas-mla]",
              "RETURN",
              "    IF (",
              "        NOT ISBLANK ( QtdeUltimaData ),",
              "        DIVIDE ( QtdeAtual - QtdeUltimaData, QtdeUltimaData, 0 ),",
              "        BLANK ()",
              "    )"
            ],
            "lineageTag": "e79d8084-a25f-4567-8544-bf9d7e10035d"
          },
          {
            "name": "% Crescimento Semana-mla",
            "displayFolder": "Robo Compras - MLA",
            "expression": [
              "VAR UltimaSemana =",
              "    CALCULATE (",
              "        MAX ( dCalendario[Date] ),",
              "        FILTER (",
              "            ALL ( dCalendario ),",
              "            dCalendario[Date] < MAX ( dCalendario[Date] )",
              "                && WEEKNUM ( dCalendario[Date], 2 ) < WEEKNUM ( MAX ( dCalendario[Date] ), 2 )",
              "                && NOT ( ISBLANK ( [Qtde Linhas-mla] ) )",
              "        )",
              "    )",
              "VAR QtdeUltimaSemana =",
              "    CALCULATE ( [Qtde Linhas-mla], dCalendario[Date] = UltimaSemana )",
              "VAR QtdeAtual = [Qtde Linhas-mla]",
              "RETURN",
              "    IF (",
              "        NOT ISBLANK ( QtdeUltimaSemana ),",
              "        DIVIDE ( QtdeAtual - QtdeUltimaSemana, QtdeUltimaSemana, 0 ),",
              "        BLANK ()",
              "    )"
            ],
            "lineageTag": "52d962c4-f4fc-4cd0-8674-3da51dbed928"
          },
          {
            "name": "% Crescimento Mes-mla",
            "displayFolder": "Robo Compras - MLA",
            "expression": [
              "VAR UltimoMes =",
              "    MONTH(CALCULATE (",
              "        MAX ( dCalendario[Date] ),",
              "        FILTER (",
              "            ALL ( dCalendario ),",
              "            dCalendario[Date] < MAX ( dCalendario[Date] )",
              "                && MONTH ( dCalendario[Date] ) < MONTH ( MAX ( dCalendario[Date] ) )",
              "                && YEAR ( dCalendario[Date] ) = YEAR ( MAX ( dCalendario[Date] ) )",
              "                && NOT ( ISBLANK ( [Qtde Linhas-mla] ) )",
              "        )",
              "    ))",
              "    ",
              "VAR QtdeUltimoMes =",
              "    CALCULATE ( [Qtde Linhas-mla], MONTH(dCalendario[Date]) = UltimoMes )",
              "VAR QtdeAtual = [Qtde Linhas-mla]",
              "",
              "VAR _Resultado =     IF (",
              "        NOT ISBLANK ( QtdeUltimoMes ),",
              "        DIVIDE ( QtdeAtual - QtdeUltimoMes, QtdeUltimoMes, 0 ),",
              "        BLANK ()",
              "    )",
              "RETURN _Resultado"
            ],
            "lineageTag": "8f402f45-a61f-493d-94c7-a2a1ba8913fd"
          },
          {
            "name": "_Crescimento (Formatado)-mla",
            "displayFolder": "Robo Compras - MLA",
            "expression": [
              "SWITCH (",
              "    TRUE (),",
              "    ISINSCOPE ( kms_rpa_lancamento_mla[Hora] ),",
              "        IF (",
              "            [% Crescimento Hora-mla] > 0,",
              "            FORMAT ( [% Crescimento Hora-mla], \"∆ 0%\" ),",
              "            FORMAT ( [% Crescimento Hora-mla], \"∇ 0%\" )",
              "        ),",
              "    ISINSCOPE ( dCalendario[Dia] ),",
              "        IF (",
              "            [% Crescimento Dia] > 0,",
              "            FORMAT ( [% Crescimento Dia-mla], \"∆ 0%\" ),",
              "            FORMAT ( [% Crescimento Dia-mla], \"∇ 0%\" )",
              "        ),",
              "    ISINSCOPE ( dCalendario[Semana] ),",
              "        IF (",
              "            [% Crescimento Semana-mla] > 0,",
              "            FORMAT ( [% Crescimento Semana-mla], \"∆ 0%\" ),",
              "            FORMAT ( [% Crescimento Semana-mla], \"∇ 0%\" )",
              "        ),",
              "    ISINSCOPE ( dCalendario[Mes] ),",
              "        IF (",
              "            [% Crescimento Mes-mla] > 0,",
              "            FORMAT ( [% Crescimento Mes-mla], \"∆ 0%\" ),",
              "            FORMAT ( [% Crescimento Mes-mla], \"∇ 0%\" )",
              "        ),",
              "    BLANK ()",
              ")"
            ],
            "lineageTag": "b386d73e-189f-492a-bbc0-1e0588f9e378"
          },
          {
            "name": "_Crescimento (Cores)-mla",
            "displayFolder": "Robo Compras - MLA",
            "expression": [
              "SWITCH (",
              "    TRUE (),",
              "    ISINSCOPE ( kms_rpa_lancamento_mla[Hora] ), IF ( [% Crescimento Hora-mla] < 0.001, \"#FF0000\", \"#008000\" ),",
              "    ISINSCOPE ( dCalendario[Dia] ), IF ( [% Crescimento Dia-mla] < 0.001, \"#FF0000\", \"#008000\" ),",
              "    ISINSCOPE ( dCalendario[Semana] ), IF ( [% Crescimento Semana-mla] < 0.001, \"#FF0000\", \"#008000\" ),",
              "    ISINSCOPE ( dCalendario[Mes] ), IF ( [% Crescimento Mes-mla] < 0.001, \"#FF0000\", \"#008000\" ),",
              "    BLANK ()",
              ")"
            ],
            "lineageTag": "97a2f7ac-119e-48a1-8794-bee48ed5433b"
          },
          {
            "name": "Qtde Linhas-axeler",
            "displayFolder": "Robo Comercial - Axeler",
            "expression": "countrows(kms_rpa_axeler)",
            "lineageTag": "daf35887-4df8-4d85-a348-44e204fde04b"
          },
          {
            "name": "(HS) Economia-axeler",
            "displayFolder": "Robo Comercial - Axeler",
            "expression": "sum(kms_rpa_axeler[qtde_horas_economizadas])",
            "lineageTag": "ecb20b65-11e9-4b27-b2c8-8fb3d9530774"
          },
          {
            "name": "R$ Est. Economia-axeler",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "displayFolder": "Robo Comercial - Axeler",
            "expression": "[(HS) Economia-axeler] * 50",
            "formatString": "R$ #,#0.00",
            "lineageTag": "f482e58a-b196-40a3-a3f1-102ff30aff64"
          },
          {
            "name": "Último Processo-axeler",
            "displayFolder": "Robo Comercial - Axeler",
            "expression": "max(kms_rpa_axeler[data_processamento])",
            "lineageTag": "4bebb2e5-1037-4c98-8d17-d838787cebee"
          },
          {
            "name": "Qtde Dias Do Último-axeler",
            "displayFolder": "Robo Comercial - Axeler",
            "expression": "DATEDIFF([Último Processo-axeler], NOW(), DAY)",
            "lineageTag": "7b785863-a403-4338-abaa-c82c8a3447ff"
          },
          {
            "name": "% Qtde Linhas-axeler",
            "displayFolder": "Robo Comercial - Axeler",
            "expression": [
              "DIVIDE (",
              "    [Qtde Linhas-axeler],",
              "    CALCULATE ( [Qtde Linhas-axeler], REMOVEFILTERS ( 'kms_rpa_axeler' ) ),",
              "    0",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "c2596380-2a16-4579-98db-1443e8e3de08"
          },
          {
            "name": "% Crescimento Hora-axeler",
            "displayFolder": "Robo Comercial - Axeler",
            "expression": [
              "VAR UltimaDataHora =",
              "    CALCULATE (",
              "        MAX ( kms_rpa_axeler[hora_processamento] ),",
              "        FILTER (",
              "            ALL ( kms_rpa_axeler ),",
              "            kms_rpa_axeler[hora_processamento] < MAX ( kms_rpa_axeler[hora_processamento] )",
              "                && NOT ( ISBLANK ( [Qtde Linhas-axeler] ) )",
              "        )",
              "    )",
              "VAR QtdeUltimaHora =",
              "    CALCULATE ( [Qtde Linhas-axeler], kms_rpa_axeler[hora_processamento] = UltimaDataHora )",
              "VAR QtdeAtual = [Qtde Linhas-axeler]",
              "RETURN",
              "    IF (",
              "        NOT ISBLANK ( QtdeUltimaHora ),",
              "        DIVIDE ( QtdeAtual - QtdeUltimaHora, QtdeUltimaHora, 0 ),",
              "        BLANK ()",
              "    )"
            ],
            "lineageTag": "134e4c24-7b65-4524-960e-fb676828c5ab"
          },
          {
            "name": "% Crescimento Dia-axeler",
            "displayFolder": "Robo Comercial - Axeler",
            "expression": [
              "VAR UltimaData =",
              "    CALCULATE (",
              "        MAX ( dCalendario[Date] ),",
              "        FILTER (",
              "            ALL ( dCalendario ),",
              "            dCalendario[Date] < MAX ( dCalendario[Date] )",
              "                && NOT ( ISBLANK ( [Qtde Linhas-axeler] ) )",
              "        )",
              "    )",
              "VAR QtdeUltimaData =",
              "    CALCULATE ( [Qtde Linhas-axeler], dCalendario[Date] = UltimaData )",
              "VAR QtdeAtual = [Qtde Linhas-axeler]",
              "RETURN",
              "    IF (",
              "        NOT ISBLANK ( QtdeUltimaData ),",
              "        DIVIDE ( QtdeAtual - QtdeUltimaData, QtdeUltimaData, 0 ),",
              "        BLANK ()",
              "    )"
            ],
            "lineageTag": "1a453832-14f4-4696-b83c-2592c6c0fc28"
          },
          {
            "name": "% Crescimento Semana-axeler",
            "displayFolder": "Robo Comercial - Axeler",
            "expression": [
              "VAR UltimaSemana =",
              "    CALCULATE (",
              "        MAX ( dCalendario[Date] ),",
              "        FILTER (",
              "            ALL ( dCalendario ),",
              "            dCalendario[Date] < MAX ( dCalendario[Date] )",
              "                && WEEKNUM ( dCalendario[Date], 2 ) < WEEKNUM ( MAX ( dCalendario[Date] ), 2 )",
              "                && NOT ( ISBLANK ( [Qtde Linhas-axeler] ) )",
              "        )",
              "    )",
              "VAR QtdeUltimaSemana =",
              "    CALCULATE ( [Qtde Linhas-axeler], dCalendario[Date] = UltimaSemana )",
              "VAR QtdeAtual = [Qtde Linhas-axeler]",
              "RETURN",
              "    IF (",
              "        NOT ISBLANK ( QtdeUltimaSemana ),",
              "        DIVIDE ( QtdeAtual - QtdeUltimaSemana, QtdeUltimaSemana, 0 ),",
              "        BLANK ()",
              "    )"
            ],
            "lineageTag": "1abb854e-5833-4afd-9c29-8204073c9667"
          },
          {
            "name": "% Crescimento Mes-axeler",
            "displayFolder": "Robo Comercial - Axeler",
            "expression": [
              "VAR UltimoMes =",
              "    MONTH(CALCULATE (",
              "        MAX ( dCalendario[Date] ),",
              "        FILTER (",
              "            ALL ( dCalendario ),",
              "            dCalendario[Date] < MAX ( dCalendario[Date] )",
              "                && MONTH ( dCalendario[Date] ) < MONTH ( MAX ( dCalendario[Date] ) )",
              "                && YEAR ( dCalendario[Date] ) = YEAR ( MAX ( dCalendario[Date] ) )",
              "                && NOT ( ISBLANK ( [Qtde Linhas-axeler] ) )",
              "        )",
              "    ))",
              "    ",
              "VAR QtdeUltimoMes =",
              "    CALCULATE ( [Qtde Linhas-axeler], MONTH(dCalendario[Date]) = UltimoMes )",
              "VAR QtdeAtual = [Qtde Linhas-axeler]",
              "",
              "VAR _Resultado =     IF (",
              "        NOT ISBLANK ( QtdeUltimoMes ),",
              "        DIVIDE ( QtdeAtual - QtdeUltimoMes, QtdeUltimoMes, 0 ),",
              "        BLANK ()",
              "    )",
              "RETURN _Resultado"
            ],
            "lineageTag": "335eea2e-64d2-498c-a097-a1e03764c242"
          },
          {
            "name": "_Crescimento (Formatado)-axeler",
            "displayFolder": "Robo Comercial - Axeler",
            "expression": [
              "SWITCH (",
              "    TRUE (),",
              "    ISINSCOPE ( kms_rpa_axeler[hora_processamento] ),",
              "        IF (",
              "            [% Crescimento Hora-axeler] > 0,",
              "            FORMAT ( [% Crescimento Hora-axeler], \"∆ 0%\" ),",
              "            FORMAT ( [% Crescimento Hora-axeler], \"∇ 0%\" )",
              "        ),",
              "    ISINSCOPE ( dCalendario[Dia] ),",
              "        IF (",
              "            [% Crescimento Dia] > 0,",
              "            FORMAT ( [% Crescimento Dia-axeler], \"∆ 0%\" ),",
              "            FORMAT ( [% Crescimento Dia-axeler], \"∇ 0%\" )",
              "        ),",
              "    ISINSCOPE ( dCalendario[Semana] ),",
              "        IF (",
              "            [% Crescimento Semana-axeler] > 0,",
              "            FORMAT ( [% Crescimento Semana-axeler], \"∆ 0%\" ),",
              "            FORMAT ( [% Crescimento Semana-axeler], \"∇ 0%\" )",
              "        ),",
              "    ISINSCOPE ( dCalendario[Mes] ),",
              "        IF (",
              "            [% Crescimento Mes-axeler] > 0,",
              "            FORMAT ( [% Crescimento Mes-axeler], \"∆ 0%\" ),",
              "            FORMAT ( [% Crescimento Mes-axeler], \"∇ 0%\" )",
              "        ),",
              "    BLANK ()",
              ")"
            ],
            "lineageTag": "d7ec040f-524a-43f2-8322-1b784a3dd76e"
          },
          {
            "name": "_Crescimento (Cores)-axeler",
            "displayFolder": "Robo Comercial - Axeler",
            "expression": [
              "SWITCH (",
              "    TRUE (),",
              "    ISINSCOPE ( kms_rpa_axeler[hora_processamento] ), IF ( [% Crescimento Hora-axeler] < 0.001, \"#FF0000\", \"#008000\" ),",
              "    ISINSCOPE ( dCalendario[Dia] ), IF ( [% Crescimento Dia-axeler] < 0.001, \"#FF0000\", \"#008000\" ),",
              "    ISINSCOPE ( dCalendario[Semana] ), IF ( [% Crescimento Semana-axeler] < 0.001, \"#FF0000\", \"#008000\" ),",
              "    ISINSCOPE ( dCalendario[Mes] ), IF ( [% Crescimento Mes-axeler] < 0.001, \"#FF0000\", \"#008000\" ),",
              "    BLANK ()",
              ")"
            ],
            "lineageTag": "f0468f86-6ea3-49c6-8d56-a155fb79d03e"
          },
          {
            "name": "Dias de Vida-axeler",
            "displayFolder": "Robo Comercial - Axeler",
            "expression": "DISTINCTCOUNT(kms_rpa_axeler[data_processamento])",
            "formatString": "0",
            "lineageTag": "51cf914d-da24-456c-9489-166e6949dc23"
          },
          {
            "name": "Dias de Vida-otif",
            "displayFolder": "Robo Compras - OTIF KBI",
            "expression": "DISTINCTCOUNT(kms_rpa_otif_kbi[data_processamento])",
            "formatString": "0",
            "lineageTag": "41986e58-dd32-4099-9dc1-31cae4de306f"
          },
          {
            "name": "Dias de Vida-mla",
            "displayFolder": "Robo Compras - MLA",
            "expression": "DISTINCTCOUNT(kms_rpa_lancamento_mla[Data])",
            "formatString": "0",
            "lineageTag": "5ff5084b-cae5-4c9a-b44f-8166ceadaf65"
          },
          {
            "name": "Dias de Vida-LancamentoQuirius",
            "displayFolder": "Robo Fiscal - Lancamento Fretes",
            "expression": "DISTINCTCOUNT(fLancamentoQuirius[Data])",
            "formatString": "0",
            "lineageTag": "19e3b042-cb49-4d54-abbf-cd3c7f7ae11d"
          }
        ],
        "partitions": [
          {
            "name": "_Medidas",
            "mode": "import",
            "source": {
              "expression": "{1}",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "dCalendario",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "bbe3b2b1c39b4b3e80be28b82208d4c0"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "0884b860-517a-4922-a41f-f6cd6ba3f774",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "3d5edd69-f89d-4097-9ae1-85679c5587d5",
            "sourceColumn": "[Ano]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Mes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "0fb2020c-75fa-4756-9c4c-386380835dc1",
            "sortByColumn": "IDanoEmes",
            "sourceColumn": "[Mes]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "fce8aab5-f2d1-426a-87fb-325f817f1ffd",
            "sortByColumn": "Date",
            "sourceColumn": "[Dia]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Semana",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "1862008e-43ed-411a-93cd-943548d9787d",
            "sourceColumn": "[Semana]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Dia da Semana",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "3ec2cc61-9271-4f9d-b7d4-56c17b34bcd4",
            "sortByColumn": "Nª Dia da Semana",
            "sourceColumn": "[Dia da Semana]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Nª Dia da Semana",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "4c445a2b-c0a6-42f2-9a82-739475d5972e",
            "sourceColumn": "[Nª Dia da Semana]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "IDanoEmes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "dCalendario[Ano] * 100 +MONTH([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "012f03aa-6259-4d96-9604-27a0f7827555",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "AnoMes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "3439cd9f-4029-42e2-95ba-178eb52c43b7",
            "sourceColumn": "[AnoMes]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Mês e Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "46aa6801-448f-4650-9401-5426210d721c",
            "sourceColumn": "[Mês e Ano]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "SemanaDoMes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "VAR PrimeiraSemanaAno = WEEKNUM(DATE(YEAR([Date]), MONTH([Date]), 1))",
              "VAR SemanaAtualAno = WEEKNUM([Date])",
              "RETURN SemanaAtualAno - PrimeiraSemanaAno"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "d3ffbbaf-6e0c-4adc-811c-7822f56b7197",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "d159c82a-e4b3-4293-aa98-3848f4db8c8c",
        "partitions": [
          {
            "name": "dCalendario",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "VAR _dataMinima = MIN(MIN(MIN(fLancamentoQuirius[Lançado Quirius]), MIN(kms_rpa_otif_kbi[data_processamento])), min(kms_rpa_axeler[data_processamento]))",
                "VAR _dataMaxima = MAX(MAX(MAX(fLancamentoQuirius[Lançado Quirius]), MAX(kms_rpa_otif_kbi[data_processamento])), MAX(kms_rpa_axeler[data_processamento]))",
                "RETURN",
                "ADDCOLUMNS(",
                "    CALENDAR(",
                "        DATE(YEAR(_dataMinima), MONTH(_dataMinima), DAY(_dataMinima)),",
                "        DATE(YEAR(_dataMaxima), MONTH(_dataMaxima), DAY(_dataMaxima))",
                "    ),",
                "    \"Ano\", YEAR([Date]),",
                "    \"Mes\", FORMAT([Date], \"MMM\") & \"/\" & YEAR([Date]),",
                "    \"AnoMes\", YEAR([Date]) * 100 + MONTH([Date]),",
                "    \"Semana\", WEEKNUM([Date]),",
                "    \"Dia\", ",
                "        VAR VdiaMes = DAY([Date])",
                "        VAR VdiaSemana = SWITCH(",
                "            WEEKDAY([Date]),",
                "            1, \"Dom\",",
                "            2, \"Seg\",",
                "            3, \"Ter\",",
                "            4, \"Qua\",",
                "            5, \"Qui\",",
                "            6, \"Sex\",",
                "            7, \"Sáb\"",
                "        )",
                "        RETURN VdiaSemana & \"-\" & VdiaMes,",
                "    \"Dia da Semana\", SWITCH(",
                "            WEEKDAY([Date]),",
                "            1, \"Dom\",",
                "            2, \"Seg\",",
                "            3, \"Ter\",",
                "            4, \"Qua\",",
                "            5, \"Qui\",",
                "            6, \"Sex\",",
                "            7, \"Sáb\"",
                "        ),",
                "    \"Nª Dia da Semana\", WEEKDAY([Date]),",
                "    \"Mês e Ano\", FORMAT([Date], \"DD/YYYY\")",
                ")",
                ""
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "fLancamentoQuirius",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "Lançado Quirius",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "4b4ed59d-1e70-4333-891d-7b420c115c3d",
            "sourceColumn": "Lançado Quirius",
            "summarizeBy": "none"
          },
          {
            "name": "Ordem",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5190af5b-88cb-4db1-a5c4-02651d7efc94",
            "sourceColumn": "Ordem",
            "summarizeBy": "none"
          },
          {
            "name": "Nº Documento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b23e90da-10be-49cc-b3b8-7e8d9bbbf9f7",
            "sourceColumn": "Nº Documento",
            "summarizeBy": "none"
          },
          {
            "name": "DATA VENCIMENTO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6a984136-31e0-4e2d-87c6-109797f34eb1",
            "sourceColumn": "DATA VENCIMENTO",
            "summarizeBy": "sum"
          },
          {
            "name": "CFOP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b11c33d4-5848-4350-bbfc-33e72bae7e2f",
            "sourceColumn": "CFOP",
            "summarizeBy": "sum"
          },
          {
            "name": "DATA DE EMISSÃO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "53f4247e-d989-484b-b7bd-acda0ff0607a",
            "sourceColumn": "DATA DE EMISSÃO",
            "summarizeBy": "sum"
          },
          {
            "name": "Data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "efe5fe0e-ffad-4384-ae3d-2ab922429333",
            "sourceColumn": "Data",
            "summarizeBy": "none"
          },
          {
            "name": "Hora",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "826e7990-e1ba-4366-ba26-0f1ad377e633",
            "sourceColumn": "Hora",
            "summarizeBy": "sum"
          },
          {
            "name": "Minuto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "439944fd-ff9a-4f82-b446-7e8f5bccd90f",
            "sourceColumn": "Minuto",
            "summarizeBy": "sum"
          },
          {
            "name": "Segundo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "3810f5ae-4996-4d1b-acef-aed5efa93c28",
            "sourceColumn": "Segundo",
            "summarizeBy": "sum"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "947c798a-3550-4430-bf1e-879e386e18d9",
            "sourceColumn": "Mês",
            "summarizeBy": "sum"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "80d194f2-992e-4d3f-b556-02e956acd369",
            "sourceColumn": "Ano",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "c65f66d9-8fb5-4902-b092-0d039fd0f46d",
        "partitions": [
          {
            "name": "fLancamentoQuirius",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Folder.Files(\"\\\\forest.local\\dfs\\Brazil\\Trabalho\\Fin\\Fiscal\\ARQUIVO FRETE RPA\"),",
                "    #\"\\\\forest local\\dfs\\Brazil\\Trabalho\\Fin\\Fiscal\\ARQUIVO FRETE RPA\\Bases\\_database_rpa_fretes xlsx\" = Fonte{[#\"Folder Path\"=\"\\\\forest.local\\dfs\\Brazil\\Trabalho\\Fin\\Fiscal\\ARQUIVO FRETE RPA\\\", Name=\"database_rpa_fretes.xlsx\"]}[Content],",
                "    #\"Pasta de Trabalho Importada do Excel\" = Excel.Workbook(#\"\\\\forest local\\dfs\\Brazil\\Trabalho\\Fin\\Fiscal\\ARQUIVO FRETE RPA\\Bases\\_database_rpa_fretes xlsx\"),",
                "    Sheet1_Sheet = #\"Pasta de Trabalho Importada do Excel\"{[Item=\"Sheet1\", Kind=\"Sheet\"]}[Data],",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),",
                "    #\"Linhas Filtradas1\" = Table.SelectRows(#\"Cabeçalhos Promovidos\", each [Lançado Quirius] <> null and [Lançado Quirius] <> \"\"),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(",
                "        #\"Linhas Filtradas1\",",
                "        {",
                "            {\"Lançado Quirius\", type text},",
                "            {\"Lançado Totvs\", type text},",
                "            {\"Ordem\", Int64.Type},",
                "            {\"Nº Documento\", Int64.Type},",
                "            {\"DATA VENCIMENTO\", Int64.Type},",
                "            {\"CFOP\", Int64.Type},",
                "            {\"DATA DE EMISSÃO\", Int64.Type}",
                "        }",
                "    ),",
                "    #\"Valor Substituído\" = Table.ReplaceValue(#\"Tipo Alterado\", \"ok\", \"\", Replacer.ReplaceText, {\"Lançado Quirius\"}),",
                "    #\"Valor Substituído1\" = Table.ReplaceValue(#\"Valor Substituído\", \"Quirius - RPA - \", \"\", Replacer.ReplaceText, {\"Lançado Quirius\"}),",
                "    #\"Linhas Filtradas\" = Table.SelectRows(#\"Valor Substituído1\", each ([Lançado Quirius] <> \"\")),",
                "    #\"Outras Colunas Removidas\" = Table.SelectColumns(",
                "        #\"Linhas Filtradas\",",
                "        {\"Lançado Quirius\", \"Ordem\", \"Nº Documento\", \"DATA VENCIMENTO\", \"CFOP\", \"DATA DE EMISSÃO\"}",
                "    ),",
                "    // Conversão da coluna \"Lançado Quirius\" de texto para datetime",
                "    #\"Lançado Quirius Convertido\" = Table.TransformColumns(",
                "        #\"Outras Colunas Removidas\",",
                "        {",
                "            {\"Lançado Quirius\", each ",
                "                let",
                "                    valorTexto = Text.From(_),              // Garante que o valor seja tratado como texto",
                "                    valorLimpo = Text.Trim(valorTexto),       // Remove espaços em branco",
                "                    // Tenta converter para número (caso o valor seja um serial Excel)",
                "                    valorSerialTry = try Number.FromText(valorLimpo, \"pt-BR\")",
                "                in",
                "                    if valorSerialTry[HasError] then",
                "                        // Se a conversão para número falhar, tenta converter como data/hora já formatada",
                "                        DateTime.FromText(valorLimpo)",
                "                    else",
                "                        let",
                "                            valorSerial = valorSerialTry[Value],",
                "                            diasInteiros = Number.RoundDown(valorSerial),       // Obtém a parte inteira (dias)",
                "                            segundosFracao = (valorSerial - diasInteiros) * 86400 // Converte a fração do dia em segundos",
                "                        in",
                "                            #datetime(1899, 12, 30, 0, 0, 0) + #duration(diasInteiros, 0, 0, segundosFracao)",
                "            , type datetime}",
                "        }",
                "    ),",
                "    #\"Ordem Alterado\" = Table.TransformColumnTypes(#\"Lançado Quirius Convertido\", {",
                "        {\"Ordem\", type text},",
                "        {\"Nº Documento\", type text}",
                "    }),",
                "    #\"Data Inserida\" = Table.AddColumn(#\"Ordem Alterado\", \"Data\", each DateTime.Date([Lançado Quirius]), type date),",
                "    #\"Hora Inserida\" = Table.AddColumn(#\"Data Inserida\", \"Hora\", each Time.Hour([Lançado Quirius]), Int64.Type),",
                "    #\"Minuto Inserido\" = Table.AddColumn(#\"Hora Inserida\", \"Minuto\", each Time.Minute([Lançado Quirius]), Int64.Type),",
                "    #\"Segundo Inserido\" = Table.AddColumn(#\"Minuto Inserido\", \"Segundo\", each Time.Second([Lançado Quirius]), type number),",
                "    #\"Mês Inserido\" = Table.AddColumn(#\"Segundo Inserido\", \"Mês\", each Date.Month([Lançado Quirius]), Int64.Type),",
                "    #\"Ano Inserido\" = Table.AddColumn(#\"Mês Inserido\", \"Ano\", each Date.Year([Lançado Quirius]), Int64.Type),",
                "    #\"Duplicatas Removidas\" = Table.Distinct(#\"Ano Inserido\")",
                "in",
                "    #\"Duplicatas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Parametro-Fiscal-Fretes",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "9bbf945d34e84197a83dfb8184c47275"
          }
        ],
        "columns": [
          {
            "name": "Parâmetro",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "4d4711f4-db15-4a27-afa1-eeae47e58d42",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Parâmetro Campos"
                }
              ]
            },
            "sortByColumn": "Parâmetro Pedido",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Parâmetro Campos",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "5cd66cb7-727a-4d7c-a73a-c7129948bb22",
            "sortByColumn": "Parâmetro Pedido",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Parâmetro Pedido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "08dd06ce-e0a1-4f21-a4bb-7b8535dfe32a",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "457bce80-0361-4006-a1c8-c59b1cfa32a0",
        "partitions": [
          {
            "name": "Parametro-Fiscal-Fretes",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Horas Economizadas\", NAMEOF('_Medidas'[(HS) Economia]), 0),",
                "    (\"R$ Est. Economia\", NAMEOF('_Medidas'[R$ Est. Economia]), 1)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "kms_rpa_otif_kbi",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "qtde_processos_total",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "67efd51a-97b6-4a78-ba59-d0ecae2b3021",
            "sourceColumn": "qtde_processos_total",
            "summarizeBy": "sum"
          },
          {
            "name": "fonte_arquivo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e1010c22-42e9-4511-8ae7-8c057b6ecbf6",
            "sourceColumn": "fonte_arquivo",
            "summarizeBy": "none"
          },
          {
            "name": "qtde_processos_com_variacao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "bded7133-c31e-441e-92b2-d1c01c9ccce8",
            "sourceColumn": "qtde_processos_com_variacao",
            "summarizeBy": "sum"
          },
          {
            "name": "data_processamento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "6a210861-1420-4254-aa77-0cf680c2a8ce",
            "sourceColumn": "data_processamento",
            "summarizeBy": "none"
          },
          {
            "name": "hora_processamento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "4ea4c216-c51b-4a7c-94da-0dafd89f8963",
            "sourceColumn": "hora_processamento",
            "summarizeBy": "none"
          },
          {
            "name": "estimativa_horas_economizadas",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6114f4fa-ba2c-441f-947e-2524a2fed315",
            "sourceColumn": "estimativa_horas_economizadas",
            "summarizeBy": "sum"
          },
          {
            "name": "estimativa_dinheiro_economizado",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "90e1623e-e347-45fb-92b1-027e0808c0f1",
            "sourceColumn": "estimativa_dinheiro_economizado",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "36914237-47b8-4e66-b342-dc674385ce71",
        "partitions": [
          {
            "name": "kms_rpa_otif_kbi",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Sql.Database(\"10.105.40.196\\powerbi\", \"idba_komatsu\", [Query=\"select * from DIM_RPA_OTIF_KBI\"]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(Fonte,{{\"data_processamento\", type date}})",
                "in",
                "    #\"Tipo Alterado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Parametro-Compras-KBI",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "8cd662cf86f140ffb6c6b4e9b3f4526a"
          }
        ],
        "columns": [
          {
            "name": "Parâmetro",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "8fc82aa0-d13f-4cb7-8f1b-7d784383a3c4",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Parâmetro Campos"
                }
              ]
            },
            "sortByColumn": "Parâmetro Pedido",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Parâmetro Campos",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "20feaf95-dc55-4616-bb7b-0fd2dafee3f2",
            "sortByColumn": "Parâmetro Pedido",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Parâmetro Pedido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "5ade9b46-c6f6-4f81-bf5d-2e01e94f3c72",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "6f8745ed-acf6-479f-b7d5-9b4cd6f22014",
        "partitions": [
          {
            "name": "Parametro-Compras-KBI",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"(HS) Economia\", NAMEOF('_Medidas'[(HS) Economia-kbi]), 0),",
                "    (\"R$ Est. Economia\", NAMEOF('_Medidas'[R$ Est. Economia-kbi]), 1)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "kms_rpa_lancamento_mla",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Estabelecimento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ddd63578-20ee-4f60-aa08-6aa0f6ae6c64",
            "sourceColumn": "Estabelecimento",
            "summarizeBy": "none"
          },
          {
            "name": "CodigoDoitem",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f2bd6a30-c946-447f-b0f3-18d8eb772e3f",
            "sourceColumn": "CodigoDoitem",
            "summarizeBy": "none"
          },
          {
            "name": "CentroDeCusto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "941e7461-4431-4744-82c9-c9ee3132f5e4",
            "sourceColumn": "CentroDeCusto",
            "summarizeBy": "none"
          },
          {
            "name": "ValorSimbolico",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "46f663bf-985e-4e6d-850f-09af555d8edf",
            "sourceColumn": "ValorSimbolico",
            "summarizeBy": "sum"
          },
          {
            "name": "QtdeRequisitada",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "91c092e3-07ab-46bf-b259-ca15bf05543c",
            "sourceColumn": "QtdeRequisitada",
            "summarizeBy": "sum"
          },
          {
            "name": "QuantidadeDelinhasOrdem",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "009a4b95-1861-46cc-8085-bc2a6e0bc696",
            "sourceColumn": "QuantidadeDelinhasOrdem",
            "summarizeBy": "sum"
          },
          {
            "name": "UnidadeDeNegocio",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7f45f6f8-eccd-4d07-a0fd-d9d09c234486",
            "sourceColumn": "UnidadeDeNegocio",
            "summarizeBy": "none"
          },
          {
            "name": "Log",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "6cfbcde0-40eb-4f56-986c-c27b1da62221",
            "sourceColumn": "Log",
            "summarizeBy": "none"
          },
          {
            "name": "Data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "6336eb47-cd13-40cf-a91c-4cbe76f90c4c",
            "sourceColumn": "Data",
            "summarizeBy": "none"
          },
          {
            "name": "Hora",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "ce2a7139-8114-4944-a72b-69a8fe5f89c8",
            "sourceColumn": "Hora",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "822ac9b3-7841-4b0b-952a-cd74d84c1c5f",
        "partitions": [
          {
            "name": "kms_rpa_lancamento_mla",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Excel.Workbook(File.Contents(\"\\\\brpin-inf012\\Trabalho\\Log\\Supri\\ROBO MLA\\Planilha Robo.xlsx\"), null, true),",
                "    Sheet1_Sheet = Fonte{[Item=\"Sheet1\",Kind=\"Sheet\"]}[Data],",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"Estabelecimento\", type text}, {\"CodigoDoitem\", type text}, {\"CentroDeCusto\", type text}, {\"ValorSimbolico\", Int64.Type}, {\"QtdeRequisitada\", Int64.Type}, {\"QuantidadeDelinhasOrdem\", Int64.Type}, {\"UnidadeDeNegocio\", type text}, {\"Log\", type datetime}}),",
                "    #\"Data Inserida\" = Table.AddColumn(#\"Tipo Alterado\", \"Data\", each DateTime.Date([Log]), type date),",
                "    #\"Hora Inserida\" = Table.AddColumn(#\"Data Inserida\", \"Hora\", each DateTime.Time([Log]), type time)",
                "in",
                "    #\"Hora Inserida\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Parametro-Compras-MLA",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "ceed98f374904f5bac47e9017ceab50a"
          }
        ],
        "columns": [
          {
            "name": "Parâmetro",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "3bfe967f-03da-46af-b82a-d226e2689731",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Parâmetro Campos"
                }
              ]
            },
            "sortByColumn": "Parâmetro Pedido",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Parâmetro Campos",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "c272bbba-2b9e-4b57-997d-77ad39d96c52",
            "sortByColumn": "Parâmetro Pedido",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Parâmetro Pedido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "e845d5b3-6def-4d24-b988-ce92b8cb0245",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "d551a36a-21f5-4b43-84cc-4cee0e3cd5ae",
        "partitions": [
          {
            "name": "Parametro-Compras-MLA",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"(HS) Economia-mla\", NAMEOF('_Medidas'[(HS) Economia-mla]), 0),",
                "    (\"R$ Est. Economia-mla\", NAMEOF('_Medidas'[R$ Est. Economia-mla]), 1)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "kms_rpa_axeler",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "data_processamento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "37fe12e8-aaa9-4549-9208-00651a5d3e13",
            "sourceColumn": "data_processamento",
            "summarizeBy": "none"
          },
          {
            "name": "hora_processamento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "9866b34d-3ad3-4c49-b40a-857f2d760ff6",
            "sourceColumn": "hora_processamento",
            "summarizeBy": "none"
          },
          {
            "name": "qtde_horas_economizadas",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7139332b-bbc7-4ae1-af47-6d53879e5277",
            "sourceColumn": "qtde_horas_economizadas",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "29977b6b-c2ae-469b-bb12-4da1a31c5027",
        "partitions": [
          {
            "name": "kms_rpa_axeler",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Sql.Database(\"10.105.40.196\\powerbi\", \"idba_komatsu\", [Query=\"select * from DIM_RPA_AXELER\"]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(Fonte,{{\"data_processamento\", type date}})",
                "in",
                "    #\"Tipo Alterado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Parametro-Comercial-Axeler",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "af78ce684e9c4c7aa3a538a650f413f9"
          }
        ],
        "columns": [
          {
            "name": "Parâmetro",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "17801561-28d8-4c89-b447-f6b624a0d49a",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Parâmetro Campos"
                }
              ]
            },
            "sortByColumn": "Parâmetro Pedido",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Parâmetro Campos",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "229f61c8-0d0f-41d1-8d9b-5d08c91090ee",
            "sortByColumn": "Parâmetro Pedido",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Parâmetro Pedido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "eb10eb25-e360-4d86-bb60-3a80abb9d2e5",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "2224a3a9-d296-434a-ba36-0c829f75f984",
        "partitions": [
          {
            "name": "Parametro-Comercial-Axeler",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"(HS) Economia-axeler\", NAMEOF('_Medidas'[(HS) Economia-axeler]), 0),",
                "    (\"R$ Est. Economia-axeler\", NAMEOF('_Medidas'[R$ Est. Economia-axeler]), 1)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}