{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"fLancamentoQuirius\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.139.2054.0 (24.12)+334ca1c95b576cc53924655643b0d36f21caac55"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\",\"DaxQueryView_Desktop\"]"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      }
    ],
    "culture": "pt-BR",
    "cultures": [
      {
        "name": "pt-BR",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "26414c7e-8921-4089-b5c5-853b11d77641",
        "fromColumn": "Lançado Quirius",
        "fromTable": "fLancamentoQuirius",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_2444c19a-b7a0-4d4c-8a2b-eebc82084acc"
      },
      {
        "name": "d208b67b-8305-45c3-b305-ab201ced58c9",
        "fromColumn": "Date",
        "fromTable": "dCalendario",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_9e933f3c-1719-47c5-a911-7812a625a499"
      },
      {
        "name": "705070dc-0232-5634-103b-ae6f3ec16f1a",
        "fromColumn": "Data",
        "fromTable": "fLancamentoQuirius",
        "toColumn": "Date",
        "toTable": "dCalendario"
      }
    ],
    "sourceQueryCulture": "pt-BR",
    "tables": [
      {
        "name": "DateTableTemplate_aa80d22a-e63b-46d3-9983-9079862d7056",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "91c7a302-aa7a-4dbe-aa05-7eec9ce01451",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "1cbafbb6-7fe8-42c5-9bcc-d4e276b066e4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "0ee48834-e183-449c-8bb0-e89d4df98448",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "227f0034-685b-4a7a-ac20-c359fe177c46",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "49b86044-39b4-4900-96cb-2491afd33d78",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "6976f4fe-05a3-4cc9-a90d-94e773f653e7",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "8a1343fb-47d9-4010-b467-bcf6f73395f6",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "5f400369-aeb6-4149-979c-65e9b6ecf7de",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "535717f4-00d5-44e0-8440-3185d71a7787",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "c0271973-b63f-4459-9908-a004f17d34a3",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "081d4344-5151-4196-909b-7ab838228b5e",
                "ordinal": 3
              }
            ],
            "lineageTag": "86dd8ce4-5bc6-42d5-8fc6-a95cc32c3ab8"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "7e302f1a-87e1-476a-baee-8908f533fd92",
        "partitions": [
          {
            "name": "DateTableTemplate_aa80d22a-e63b-46d3-9983-9079862d7056",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "_Medidas",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "b082479044cb45ac997df4e08485d02e"
          }
        ],
        "columns": [
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "18c4ffdf-07d4-4510-9c0a-9dd0af716f00",
            "sourceColumn": "[Value]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "2c84c17f-0680-452f-9dc8-9ec63ff9459a",
        "measures": [
          {
            "name": "Qtde Notas",
            "description": "COUNTROWS ( fLancamentoQuirius )",
            "expression": "COUNTROWS ( fLancamentoQuirius )",
            "formatString": "#,#0",
            "lineageTag": "ca472473-88c6-46a5-8539-22e4fde82c15"
          },
          {
            "name": "% Crescimento Dia",
            "description": [
              "VAR UltimaData =",
              "    CALCULATE (",
              "        MAX ( dCalendario[Date] ),",
              "        FILTER (",
              "            ALL ( dCalendario ),",
              "            dCalendario[Date] < MAX ( dCalendario[Date] )",
              "                && NOT ( ISBLANK ( [Qtde Notas] ) )",
              "        )",
              "    )",
              "VAR QtdeUltimaData =",
              "    CALCULATE ( [Qtde Notas], dCalendario[Date] = UltimaData )",
              "VAR QtdeAtual = [Qtde Notas]",
              "RETURN",
              "    IF (",
              "        NOT ISBLANK ( QtdeUltimaData ),",
              "        DIVIDE ( QtdeAtual - QtdeUltimaData, QtdeUltimaData, 0 ),",
              "        BLANK ()",
              "    )"
            ],
            "expression": [
              "VAR UltimaData =",
              "    CALCULATE (",
              "        MAX ( dCalendario[Date] ),",
              "        FILTER (",
              "            ALL ( dCalendario ),",
              "            dCalendario[Date] < MAX ( dCalendario[Date] )",
              "                && NOT ( ISBLANK ( [Qtde Notas] ) )",
              "        )",
              "    )",
              "VAR QtdeUltimaData =",
              "    CALCULATE ( [Qtde Notas], dCalendario[Date] = UltimaData )",
              "VAR QtdeAtual = [Qtde Notas]",
              "RETURN",
              "    IF (",
              "        NOT ISBLANK ( QtdeUltimaData ),",
              "        DIVIDE ( QtdeAtual - QtdeUltimaData, QtdeUltimaData, 0 ),",
              "        BLANK ()",
              "    )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "d88f893c-4178-4726-85de-a63ed822eeda"
          },
          {
            "name": "_Crescimento (Formatado)",
            "description": [
              "SWITCH (",
              "    TRUE (),",
              "    ISINSCOPE ( fLancamentoQuirius[Hora] ),",
              "        IF (",
              "            [% Crescimento Hora] > 0,",
              "            FORMAT ( [% Crescimento Hora], \"∆ 0%\" ),",
              "            FORMAT ( [% Crescimento Hora], \"∇ 0%\" )",
              "        ),",
              "    ISINSCOPE ( dCalendario[Dia] ),",
              "        IF (",
              "            [% Crescimento Dia] > 0,",
              "            FORMAT ( [% Crescimento Dia], \"∆ 0%\" ),",
              "            FORMAT ( [% Crescimento Dia], \"∇ 0%\" )",
              "        ),",
              "    ISINSCOPE ( dCalendario[Semana] ),",
              "        IF (",
              "            [% Crescimento Semana] > 0,",
              "            FORMAT ( [% Crescimento Semana], \"∆ 0%\" ),",
              "            FORMAT ( [% Crescimento Semana], \"∇ 0%\" )",
              "        ),",
              "    ISINSCOPE ( dCalendario[Mes] ),",
              "        IF (",
              "            [% Crescimento Mes] > 0,",
              "            FORMAT ( [% Crescimento Mes], \"∆ 0%\" ),",
              "            FORMAT ( [% Crescimento Mes], \"∇ 0%\" )",
              "        ),",
              "    BLANK ()",
              ")"
            ],
            "expression": [
              "SWITCH (",
              "    TRUE (),",
              "    ISINSCOPE ( fLancamentoQuirius[Hora] ),",
              "        IF (",
              "            [% Crescimento Hora] > 0,",
              "            FORMAT ( [% Crescimento Hora], \"∆ 0%\" ),",
              "            FORMAT ( [% Crescimento Hora], \"∇ 0%\" )",
              "        ),",
              "    ISINSCOPE ( dCalendario[Dia] ),",
              "        IF (",
              "            [% Crescimento Dia] > 0,",
              "            FORMAT ( [% Crescimento Dia], \"∆ 0%\" ),",
              "            FORMAT ( [% Crescimento Dia], \"∇ 0%\" )",
              "        ),",
              "    ISINSCOPE ( dCalendario[Semana] ),",
              "        IF (",
              "            [% Crescimento Semana] > 0,",
              "            FORMAT ( [% Crescimento Semana], \"∆ 0%\" ),",
              "            FORMAT ( [% Crescimento Semana], \"∇ 0%\" )",
              "        ),",
              "    ISINSCOPE ( dCalendario[Mes] ),",
              "        IF (",
              "            [% Crescimento Mes] > 0,",
              "            FORMAT ( [% Crescimento Mes], \"∆ 0%\" ),",
              "            FORMAT ( [% Crescimento Mes], \"∇ 0%\" )",
              "        ),",
              "    BLANK ()",
              ")"
            ],
            "lineageTag": "dc854c0d-34f1-458f-92f2-1e8de3e9b5b6"
          },
          {
            "name": "_Crescimento (Cores)",
            "description": [
              "SWITCH (",
              "    TRUE (),",
              "    ISINSCOPE ( fLancamentoQuirius[Hora] ), IF ( [% Crescimento Hora] < 0.001, \"#FF0000\", \"#008000\" ),",
              "    ISINSCOPE ( dCalendario[Dia] ), IF ( [% Crescimento Dia] < 0.001, \"#FF0000\", \"#008000\" ),",
              "    ISINSCOPE ( dCalendario[Semana] ), IF ( [% Crescimento Semana] < 0.001, \"#FF0000\", \"#008000\" ),",
              "    ISINSCOPE ( dCalendario[Mes] ), IF ( [% Crescimento Mes] < 0.001, \"#FF0000\", \"#008000\" ),",
              "    BLANK ()",
              ")"
            ],
            "detailRowsDefinition": {
              "expression": "x1"
            },
            "expression": [
              "SWITCH (",
              "    TRUE (),",
              "    ISINSCOPE ( fLancamentoQuirius[Hora] ), IF ( [% Crescimento Hora] < 0.001, \"#FF0000\", \"#008000\" ),",
              "    ISINSCOPE ( dCalendario[Dia] ), IF ( [% Crescimento Dia] < 0.001, \"#FF0000\", \"#008000\" ),",
              "    ISINSCOPE ( dCalendario[Semana] ), IF ( [% Crescimento Semana] < 0.001, \"#FF0000\", \"#008000\" ),",
              "    ISINSCOPE ( dCalendario[Mes] ), IF ( [% Crescimento Mes] < 0.001, \"#FF0000\", \"#008000\" ),",
              "    BLANK ()",
              ")"
            ],
            "lineageTag": "cfd3bfae-95bf-4db7-a0e3-87ddd4a4cd99"
          },
          {
            "name": "% Crescimento Hora",
            "description": [
              "VAR UltimaDataHora =",
              "    CALCULATE (",
              "        MAX ( fLancamentoQuirius[Hora] ),",
              "        FILTER (",
              "            ALL ( fLancamentoQuirius ),",
              "            fLancamentoQuirius[Hora] < MAX ( fLancamentoQuirius[Hora] )",
              "                && NOT ( ISBLANK ( [Qtde Notas] ) )",
              "        )",
              "    )",
              "VAR QtdeUltimaHora =",
              "    CALCULATE ( [Qtde Notas], fLancamentoQuirius[Hora] = UltimaDataHora )",
              "VAR QtdeAtual = [Qtde Notas]",
              "RETURN",
              "    IF (",
              "        NOT ISBLANK ( QtdeUltimaHora ),",
              "        DIVIDE ( QtdeAtual - QtdeUltimaHora, QtdeUltimaHora, 0 ),",
              "        BLANK ()",
              "    )"
            ],
            "expression": [
              "VAR UltimaDataHora =",
              "    CALCULATE (",
              "        MAX ( fLancamentoQuirius[Hora] ),",
              "        FILTER (",
              "            ALL ( fLancamentoQuirius ),",
              "            fLancamentoQuirius[Hora] < MAX ( fLancamentoQuirius[Hora] )",
              "                && NOT ( ISBLANK ( [Qtde Notas] ) )",
              "        )",
              "    )",
              "VAR QtdeUltimaHora =",
              "    CALCULATE ( [Qtde Notas], fLancamentoQuirius[Hora] = UltimaDataHora )",
              "VAR QtdeAtual = [Qtde Notas]",
              "RETURN",
              "    IF (",
              "        NOT ISBLANK ( QtdeUltimaHora ),",
              "        DIVIDE ( QtdeAtual - QtdeUltimaHora, QtdeUltimaHora, 0 ),",
              "        BLANK ()",
              "    )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "d048b22b-a359-4764-9a2a-c2c3e612064b"
          },
          {
            "name": "R$ Est. Economia",
            "description": "DIVIDE ( [Qtde Notas], 50, 0 ) * 60",
            "expression": "[(HS) Economia] * 20",
            "formatString": "R$ #,#0.00",
            "lineageTag": "d82ea27e-7b1e-4168-9661-83fc9f385a0c"
          },
          {
            "name": "Último Processo",
            "description": "MAX ( fLancamentoQuirius[Lançado Quirius] )",
            "expression": "MAX ( fLancamentoQuirius[Lançado Quirius] )",
            "formatString": "Short Date",
            "lineageTag": "0cd7d9d6-eab3-4940-9035-88338b16154b"
          },
          {
            "name": "% Crescimento Semana",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": [
              "VAR UltimaSemana =",
              "    CALCULATE (",
              "        MAX ( dCalendario[Date] ),",
              "        FILTER (",
              "            ALL ( dCalendario ),",
              "            dCalendario[Date] < MAX ( dCalendario[Date] )",
              "                && WEEKNUM ( dCalendario[Date], 2 ) < WEEKNUM ( MAX ( dCalendario[Date] ), 2 )",
              "                && NOT ( ISBLANK ( [Qtde Notas] ) )",
              "        )",
              "    )",
              "VAR QtdeUltimaSemana =",
              "    CALCULATE ( [Qtde Notas], dCalendario[Date] = UltimaSemana )",
              "VAR QtdeAtual = [Qtde Notas]",
              "RETURN",
              "    IF (",
              "        NOT ISBLANK ( QtdeUltimaSemana ),",
              "        DIVIDE ( QtdeAtual - QtdeUltimaSemana, QtdeUltimaSemana, 0 ),",
              "        BLANK ()",
              "    )"
            ],
            "expression": [
              "VAR UltimaSemana =",
              "    CALCULATE (",
              "        MAX ( dCalendario[Date] ),",
              "        FILTER (",
              "            ALL ( dCalendario ),",
              "            dCalendario[Date] < MAX ( dCalendario[Date] )",
              "                && WEEKNUM ( dCalendario[Date], 2 ) < WEEKNUM ( MAX ( dCalendario[Date] ), 2 )",
              "                && NOT ( ISBLANK ( [Qtde Notas] ) )",
              "        )",
              "    )",
              "VAR QtdeUltimaSemana =",
              "    CALCULATE ( [Qtde Notas], dCalendario[Date] = UltimaSemana )",
              "VAR QtdeAtual = [Qtde Notas]",
              "RETURN",
              "    IF (",
              "        NOT ISBLANK ( QtdeUltimaSemana ),",
              "        DIVIDE ( QtdeAtual - QtdeUltimaSemana, QtdeUltimaSemana, 0 ),",
              "        BLANK ()",
              "    )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "1ddda994-4961-4d68-a0d9-335117659753"
          },
          {
            "name": "% Crescimento Mes",
            "description": [
              "VAR UltimoMes =",
              "    CALCULATE (",
              "        MAX ( dCalendario[Date] ),",
              "        FILTER (",
              "            ALL ( dCalendario ),",
              "            dCalendario[Date] < MAX ( dCalendario[Date] )",
              "                && MONTH ( dCalendario[Date] ) < MONTH ( MAX ( dCalendario[Date] ) )",
              "                && YEAR ( dCalendario[Date] ) = YEAR ( MAX ( dCalendario[Date] ) )",
              "                && NOT ( ISBLANK ( [Qtde Notas] ) )",
              "        )",
              "    )",
              "VAR QtdeUltimoMes =",
              "    CALCULATE ( [Qtde Notas], dCalendario[Date] = UltimoMes )",
              "VAR QtdeAtual = [Qtde Notas]",
              "RETURN",
              "    IF (",
              "        NOT ISBLANK ( QtdeUltimoMes ),",
              "        DIVIDE ( QtdeAtual - QtdeUltimoMes, QtdeUltimoMes, 0 ),",
              "        BLANK ()",
              "    )"
            ],
            "expression": [
              "VAR UltimoMes =",
              "    MONTH(CALCULATE (",
              "        MAX ( dCalendario[Date] ),",
              "        FILTER (",
              "            ALL ( dCalendario ),",
              "            dCalendario[Date] < MAX ( dCalendario[Date] )",
              "                && MONTH ( dCalendario[Date] ) < MONTH ( MAX ( dCalendario[Date] ) )",
              "                && YEAR ( dCalendario[Date] ) = YEAR ( MAX ( dCalendario[Date] ) )",
              "                && NOT ( ISBLANK ( [Qtde Notas] ) )",
              "        )",
              "    ))",
              "    ",
              "VAR QtdeUltimoMes =",
              "    CALCULATE ( [Qtde Notas], MONTH(dCalendario[Date]) = UltimoMes )",
              "VAR QtdeAtual = [Qtde Notas]",
              "",
              "VAR _Resultado =     IF (",
              "        NOT ISBLANK ( QtdeUltimoMes ),",
              "        DIVIDE ( QtdeAtual - QtdeUltimoMes, QtdeUltimoMes, 0 ),",
              "        BLANK ()",
              "    )",
              "RETURN _Resultado",
              ""
            ],
            "formatString": "0",
            "lineageTag": "5f11f2a9-31dc-4c5f-b514-213aef0e09bd"
          },
          {
            "name": "% Qtde Notas",
            "description": [
              "DIVIDE (",
              "    [Qtde Notas],",
              "    CALCULATE ( [Qtde Notas], ALL ( fLancamentoQuirius ) ),",
              "    0",
              ")"
            ],
            "expression": [
              "DIVIDE (",
              "    [Qtde Notas],",
              "    CALCULATE ( [Qtde Notas], ALL ( fLancamentoQuirius ) ),",
              "    0",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "3e783bfc-bca4-4f1e-b163-efebbc86940b"
          },
          {
            "name": "(HS) Economia",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "DIVIDE([Qtde Notas] * 7,60,0)",
            "lineageTag": "b00a907e-7cc1-4e3f-8e1c-eb0d2229f79b"
          }
        ],
        "partitions": [
          {
            "name": "_Medidas",
            "mode": "import",
            "source": {
              "expression": "{1}",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "dCalendario",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "bbe3b2b1c39b4b3e80be28b82208d4c0"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "0884b860-517a-4922-a41f-f6cd6ba3f774",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_9e933f3c-1719-47c5-a911-7812a625a499"
                },
                "isDefault": true,
                "relationship": "d208b67b-8305-45c3-b305-ab201ced58c9"
              }
            ]
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "3d5edd69-f89d-4097-9ae1-85679c5587d5",
            "sourceColumn": "[Ano]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Mes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "0fb2020c-75fa-4756-9c4c-386380835dc1",
            "sortByColumn": "IDanoEmes",
            "sourceColumn": "[Mes]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "fce8aab5-f2d1-426a-87fb-325f817f1ffd",
            "sortByColumn": "Date",
            "sourceColumn": "[Dia]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Semana",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "1862008e-43ed-411a-93cd-943548d9787d",
            "sourceColumn": "[Semana]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Dia da Semana",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "3ec2cc61-9271-4f9d-b7d4-56c17b34bcd4",
            "sortByColumn": "Nª Dia da Semana",
            "sourceColumn": "[Dia da Semana]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Nª Dia da Semana",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "4c445a2b-c0a6-42f2-9a82-739475d5972e",
            "sourceColumn": "[Nª Dia da Semana]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "IDanoEmes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "dCalendario[Ano] * 100 +MONTH([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "012f03aa-6259-4d96-9604-27a0f7827555",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "AnoMes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "3439cd9f-4029-42e2-95ba-178eb52c43b7",
            "sourceColumn": "[AnoMes]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Mês e Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "46aa6801-448f-4650-9401-5426210d721c",
            "sourceColumn": "[Mês e Ano]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "SemanaDoMes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "VAR PrimeiraSemanaAno = WEEKNUM(DATE(YEAR([Date]), MONTH([Date]), 1))",
              "VAR SemanaAtualAno = WEEKNUM([Date])",
              "RETURN SemanaAtualAno - PrimeiraSemanaAno"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "d3ffbbaf-6e0c-4adc-811c-7822f56b7197",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "d159c82a-e4b3-4293-aa98-3848f4db8c8c",
        "partitions": [
          {
            "name": "dCalendario",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "VAR _dataMinima = MIN(fLancamentoQuirius[Lançado Quirius])",
                "VAR _dataMaxima = MAX(fLancamentoQuirius[Lançado Quirius])",
                "RETURN",
                "ADDCOLUMNS(",
                "    CALENDAR(",
                "        DATE(YEAR(_dataMinima), MONTH(_dataMinima), DAY(_dataMinima)),",
                "        DATE(YEAR(_dataMaxima), MONTH(_dataMaxima), DAY(_dataMaxima))",
                "    ),",
                "    \"Ano\", YEAR([Date]),",
                "    \"Mes\", FORMAT([Date], \"MMM\") & \"/\" & YEAR([Date]),",
                "    \"AnoMes\", YEAR([Date]) * 100 + MONTH([Date]),",
                "    \"Semana\", WEEKNUM([Date]),",
                "    \"Dia\", ",
                "        VAR VdiaMes = DAY([Date])",
                "        VAR VdiaSemana = SWITCH(",
                "            WEEKDAY([Date]),",
                "            1, \"Dom\",",
                "            2, \"Seg\",",
                "            3, \"Ter\",",
                "            4, \"Qua\",",
                "            5, \"Qui\",",
                "            6, \"Sex\",",
                "            7, \"Sáb\"",
                "        )",
                "        RETURN VdiaSemana & \"-\" & VdiaMes,",
                "    \"Dia da Semana\", SWITCH(",
                "            WEEKDAY([Date]),",
                "            1, \"Dom\",",
                "            2, \"Seg\",",
                "            3, \"Ter\",",
                "            4, \"Qua\",",
                "            5, \"Qui\",",
                "            6, \"Sex\",",
                "            7, \"Sáb\"",
                "        ),",
                "    \"Nª Dia da Semana\", WEEKDAY([Date]),",
                "    \"Mês e Ano\", FORMAT([Date], \"DD/YYYY\")",
                ")",
                ""
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "fLancamentoQuirius",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "Lançado Quirius",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "4b4ed59d-1e70-4333-891d-7b420c115c3d",
            "sourceColumn": "Lançado Quirius",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_2444c19a-b7a0-4d4c-8a2b-eebc82084acc"
                },
                "isDefault": true,
                "relationship": "26414c7e-8921-4089-b5c5-853b11d77641"
              }
            ]
          },
          {
            "name": "Ordem",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5190af5b-88cb-4db1-a5c4-02651d7efc94",
            "sourceColumn": "Ordem",
            "summarizeBy": "none"
          },
          {
            "name": "Nº Documento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b23e90da-10be-49cc-b3b8-7e8d9bbbf9f7",
            "sourceColumn": "Nº Documento",
            "summarizeBy": "none"
          },
          {
            "name": "DATA VENCIMENTO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6a984136-31e0-4e2d-87c6-109797f34eb1",
            "sourceColumn": "DATA VENCIMENTO",
            "summarizeBy": "sum"
          },
          {
            "name": "CFOP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b11c33d4-5848-4350-bbfc-33e72bae7e2f",
            "sourceColumn": "CFOP",
            "summarizeBy": "sum"
          },
          {
            "name": "DATA DE EMISSÃO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "53f4247e-d989-484b-b7bd-acda0ff0607a",
            "sourceColumn": "DATA DE EMISSÃO",
            "summarizeBy": "sum"
          },
          {
            "name": "Data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "efe5fe0e-ffad-4384-ae3d-2ab922429333",
            "sourceColumn": "Data",
            "summarizeBy": "none"
          },
          {
            "name": "Hora",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "826e7990-e1ba-4366-ba26-0f1ad377e633",
            "sourceColumn": "Hora",
            "summarizeBy": "sum"
          },
          {
            "name": "Minuto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "439944fd-ff9a-4f82-b446-7e8f5bccd90f",
            "sourceColumn": "Minuto",
            "summarizeBy": "sum"
          },
          {
            "name": "Segundo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "3810f5ae-4996-4d1b-acef-aed5efa93c28",
            "sourceColumn": "Segundo",
            "summarizeBy": "sum"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "947c798a-3550-4430-bf1e-879e386e18d9",
            "sourceColumn": "Mês",
            "summarizeBy": "sum"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "80d194f2-992e-4d3f-b556-02e956acd369",
            "sourceColumn": "Ano",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "c65f66d9-8fb5-4902-b092-0d039fd0f46d",
        "partitions": [
          {
            "name": "fLancamentoQuirius",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Folder.Files(\"\\\\forest.local\\dfs\\Brazil\\Trabalho\\Fin\\Fiscal\\ARQUIVO FRETE RPA\"),",
                "    #\"\\\\forest local\\dfs\\Brazil\\Trabalho\\Fin\\Fiscal\\ARQUIVO FRETE RPA\\Bases\\_database_rpa_fretes xlsx\" = Fonte{[#\"Folder Path\"=\"\\\\forest.local\\dfs\\Brazil\\Trabalho\\Fin\\Fiscal\\ARQUIVO FRETE RPA\\\",Name=\"database_rpa_fretes.xlsx\"]}[Content],",
                "    #\"Pasta de Trabalho Importada do Excel\" = Excel.Workbook(#\"\\\\forest local\\dfs\\Brazil\\Trabalho\\Fin\\Fiscal\\ARQUIVO FRETE RPA\\Bases\\_database_rpa_fretes xlsx\"),",
                "    Sheet1_Sheet = #\"Pasta de Trabalho Importada do Excel\"{[Item=\"Sheet1\",Kind=\"Sheet\"]}[Data],",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"Lançado Quirius\", type text}, {\"Lançado Totvs\", type text}, {\"Ordem\", Int64.Type}, {\"Nº Documento\", Int64.Type}, {\"DATA VENCIMENTO\", Int64.Type}, {\"CFOP\", Int64.Type}, {\"DATA DE EMISSÃO\", Int64.Type}}),",
                "    #\"Valor Substituído\" = Table.ReplaceValue(#\"Tipo Alterado\",\"ok\",\"\",Replacer.ReplaceText,{\"Lançado Quirius\"}),",
                "    #\"Valor Substituído1\" = Table.ReplaceValue(#\"Valor Substituído\",\"Quirius - RPA - \",\"\",Replacer.ReplaceText,{\"Lançado Quirius\"}),",
                "    #\"Linhas Filtradas\" = Table.SelectRows(#\"Valor Substituído1\", each ([Lançado Quirius] <> \"\")),",
                "    #\"Outras Colunas Removidas\" = Table.SelectColumns(#\"Linhas Filtradas\",{\"Lançado Quirius\", \"Ordem\", \"Nº Documento\", \"DATA VENCIMENTO\", \"CFOP\", \"DATA DE EMISSÃO\"}),",
                "    #\"Tipo Alterado1\" = Table.TransformColumnTypes(#\"Outras Colunas Removidas\",{{\"Lançado Quirius\", type datetime}, {\"Ordem\", type text}, {\"Nº Documento\", type text}}),",
                "    #\"Data Inserida\" = Table.AddColumn(#\"Tipo Alterado1\", \"Data\", each DateTime.Date([Lançado Quirius]), type date),",
                "    #\"Hora Inserida\" = Table.AddColumn(#\"Data Inserida\", \"Hora\", each Time.Hour([Lançado Quirius]), Int64.Type),",
                "    #\"Minuto Inserido\" = Table.AddColumn(#\"Hora Inserida\", \"Minuto\", each Time.Minute([Lançado Quirius]), Int64.Type),",
                "    #\"Segundo Inserido\" = Table.AddColumn(#\"Minuto Inserido\", \"Segundo\", each Time.Second([Lançado Quirius]), type number),",
                "    #\"Mês Inserido\" = Table.AddColumn(#\"Segundo Inserido\", \"Mês\", each Date.Month([Lançado Quirius]), Int64.Type),",
                "    #\"Ano Inserido\" = Table.AddColumn(#\"Mês Inserido\", \"Ano\", each Date.Year([Lançado Quirius]), Int64.Type),",
                "    #\"Duplicatas Removidas\" = Table.Distinct(#\"Ano Inserido\")",
                "in",
                "    #\"Duplicatas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_2444c19a-b7a0-4d4c-8a2b-eebc82084acc",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "4c0833aa-fe45-4fd2-a3e3-34bf393bfb50",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "f72d7fe0-9bcb-49bd-aa4f-64048de4a0f2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "57573388-79e3-48d4-b319-da95071fde66",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "69ffbdcd-fb49-4489-8b12-40a24be06526",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "d90730d6-0662-4280-bb53-efe2dbdb15c2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "9f3dc66b-d859-4dbe-9772-667789508582",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "651fe6ec-d9ba-49b4-b00b-78c1c59bda10",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "ec77e3bd-4035-406b-a1fa-30ba175bfdda",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "e304f7c4-8d98-4024-8ca8-723d6fe910bc",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "20f25e12-4f09-4a47-850d-c2c07f5498b8",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "8407a262-62cb-495e-aa3a-bfbc0039b944",
                "ordinal": 3
              }
            ],
            "lineageTag": "a6b88e9e-7c85-46e5-9916-c717684ec939"
          }
        ],
        "isHidden": true,
        "lineageTag": "e9c50e0b-1b97-4e8b-9c0f-30e76b6250b5",
        "partitions": [
          {
            "name": "LocalDateTable_2444c19a-b7a0-4d4c-8a2b-eebc82084acc",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('fLancamentoQuirius'[Lançado Quirius])), 1, 1), Date(Year(MAX('fLancamentoQuirius'[Lançado Quirius])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_9e933f3c-1719-47c5-a911-7812a625a499",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "104f0a75-1f9f-4f54-b80d-fc97f154d61e",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "0b07b803-3885-43b4-95e4-af695c457e40",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "a818da26-720b-469b-a6df-35f264e43875",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "638e384a-2b1c-4a97-b54b-545dcc12a581",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "826a45cf-3378-4504-972b-5f65c1b036c5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "3d6c0930-a698-4015-a63d-25facc37a779",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "a74f03b5-21b3-4f69-9b10-f8cfc3f64a11",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "4e163a07-378b-4594-b6d9-c3a9f0ad23f2",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "c432b6fe-a31b-4c91-9a51-738fe71b6d55",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "b9b5a340-dc25-4fcc-8122-108cb1460a09",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "819000b2-94e8-44e6-8d78-ba57827465ee",
                "ordinal": 3
              }
            ],
            "lineageTag": "9a54667e-07ff-4254-a43d-b50ccf0c5fbc"
          }
        ],
        "isHidden": true,
        "lineageTag": "4e1bf909-84e1-4a59-ab72-daaabc88da64",
        "partitions": [
          {
            "name": "LocalDateTable_9e933f3c-1719-47c5-a911-7812a625a499",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dCalendario'[Date])), 1, 1), Date(Year(MAX('dCalendario'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Parâmetro",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "9bbf945d34e84197a83dfb8184c47275"
          }
        ],
        "columns": [
          {
            "name": "Parâmetro",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "4d4711f4-db15-4a27-afa1-eeae47e58d42",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Parâmetro Campos"
                }
              ]
            },
            "sortByColumn": "Parâmetro Pedido",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Parâmetro Campos",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "5cd66cb7-727a-4d7c-a73a-c7129948bb22",
            "sortByColumn": "Parâmetro Pedido",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Parâmetro Pedido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "08dd06ce-e0a1-4f21-a4bb-7b8535dfe32a",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "457bce80-0361-4006-a1c8-c59b1cfa32a0",
        "partitions": [
          {
            "name": "Parâmetro",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Horas Economizadas\", NAMEOF('_Medidas'[(HS) Economia]), 0),",
                "    (\"R$ Est. Economia\", NAMEOF('_Medidas'[R$ Est. Economia]), 1)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}